import type { AudioGenVoice } from './audio-gen-voices-service'

// 51 high quality Vietnamese preset voices from AI Dancing (audio.aidancing.net)
export const AIDANCING_PRESET_VOICES: AudioGenVoice[] = [
  {
    id: 'aidancing_0',
    voiceIndex: '0',
    label: 'Giọng Adam',
    description: 'Giọng đọc Tiếng Việt AI Dancing Giọng Adam. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/nam-vn-1.mp3',
    language: 'Vietnamese',
    gender: 'Male',
    tags: ['Vietnamese', 'Male', 'AI Dancing', 'Voice Clone'],
  },
  {
    id: 'aidancing_1',
    voiceIndex: '1',
    label: 'Trung Caha - Rõ ràng, Chắc chắn',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Trung Caha - Rõ ràng, Chắc chắn. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-1.mp3',
    language: 'Vietnamese',
    gender: 'Male',
    tags: ['Vietnamese', 'Male', 'AI Dancing', 'Voice Clone', 'Rõ ràng', 'Chắc chắn'],
  },
  {
    id: 'aidancing_2',
    voiceIndex: '2',
    label: 'Kiều Linh',
    description: 'Giọng đọc Tiếng Việt AI Dancing Kiều Linh. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-2.mp3',
    language: 'Vietnamese',
    gender: 'Female',
    tags: ['Vietnamese', 'Female', 'AI Dancing', 'Voice Clone'],
  },
  {
    id: 'aidancing_3',
    voiceIndex: '3',
    label: 'Tùng Đặng - Trầm, Ấm áp',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Tùng Đặng - Trầm, Ấm áp. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-3.mp3',
    language: 'Vietnamese',
    gender: 'Male',
    tags: ['Vietnamese', 'Male', 'AI Dancing', 'Voice Clone', 'Trầm', 'Ấm áp'],
  },
  {
    id: 'aidancing_4',
    voiceIndex: '4',
    label: 'Hạnh - Mượt mà, Rõ ràng',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Hạnh - Mượt mà, Rõ ràng. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-4.mp3',
    language: 'Vietnamese',
    gender: 'Female',
    tags: ['Vietnamese', 'Female', 'AI Dancing', 'Voice Clone', 'Mượt mà', 'Rõ ràng'],
  },
  {
    id: 'aidancing_5',
    voiceIndex: '5',
    label: 'Tùng Đặng - Ấm áp, Điềm tĩnh',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Tùng Đặng - Ấm áp, Điềm tĩnh. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-5.mp3',
    language: 'Vietnamese',
    gender: 'Male',
    tags: ['Vietnamese', 'Male', 'AI Dancing', 'Voice Clone', 'Ấm áp', 'Điềm tĩnh'],
  },
  {
    id: 'aidancing_6',
    voiceIndex: '6',
    label: 'Ngân Nguyễn',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Ngân Nguyễn. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-6.mp3',
    language: 'Vietnamese',
    gender: 'Female',
    tags: ['Vietnamese', 'Female', 'AI Dancing', 'Voice Clone'],
  },
  {
    id: 'aidancing_7',
    voiceIndex: '7',
    label: 'Triều Dương - Trầm, Điềm tĩnh',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Triều Dương - Trầm, Điềm tĩnh. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-7.mp3',
    language: 'Vietnamese',
    gender: 'Male',
    tags: ['Vietnamese', 'Male', 'AI Dancing', 'Voice Clone', 'Trầm', 'Điềm tĩnh'],
  },
  {
    id: 'aidancing_8',
    voiceIndex: '8',
    label: 'Như - Điềm tĩnh, Tự tin',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Như - Điềm tĩnh, Tự tin. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-8.mp3',
    language: 'Vietnamese',
    gender: 'Female',
    tags: ['Vietnamese', 'Female', 'AI Dancing', 'Voice Clone', 'Điềm tĩnh', 'Tự tin'],
  },
  {
    id: 'aidancing_9',
    voiceIndex: '9',
    label: 'Mai - Tự nhiên, Tươi sáng',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Mai - Tự nhiên, Tươi sáng. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-9.mp3',
    language: 'Vietnamese',
    gender: 'Female',
    tags: ['Vietnamese', 'Female', 'AI Dancing', 'Voice Clone', 'Tự nhiên', 'Tươi sáng'],
  },
  {
    id: 'aidancing_10',
    voiceIndex: '10',
    label: 'Hải Ly - Trầm, Nghiêm túc',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Hải Ly - Trầm, Nghiêm túc. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-10.mp3',
    language: 'Vietnamese',
    gender: 'Female',
    tags: ['Vietnamese', 'Female', 'AI Dancing', 'Voice Clone', 'Trầm', 'Nghiêm túc'],
  },
  {
    id: 'aidancing_11',
    voiceIndex: '11',
    label: 'Tuyết - Sắc nét, Trang trọng',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Tuyết - Sắc nét, Trang trọng. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-11.mp3',
    language: 'Vietnamese',
    gender: 'Female',
    tags: ['Vietnamese', 'Female', 'AI Dancing', 'Voice Clone', 'Sắc nét', 'Trang trọng'],
  },
  {
    id: 'aidancing_12',
    voiceIndex: '12',
    label: 'Hiền - Ấm áp, Trầm',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Hiền - Ấm áp, Trầm. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-12.mp3',
    language: 'Vietnamese',
    gender: 'Female',
    tags: ['Vietnamese', 'Female', 'AI Dancing', 'Voice Clone', 'Ấm áp', 'Trầm'],
  },
  {
    id: 'aidancing_13',
    voiceIndex: '13',
    label: 'Ninh Đôn - Trầm, Ấm áp',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Ninh Đôn - Trầm, Ấm áp. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-13.mp3',
    language: 'Vietnamese',
    gender: 'Female',
    tags: ['Vietnamese', 'Female', 'AI Dancing', 'Voice Clone', 'Trầm', 'Ấm áp'],
  },
  {
    id: 'aidancing_14',
    voiceIndex: '14',
    label: 'Sơn Trần - Thoải mái, Đối thoại',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Sơn Trần - Thoải mái, Đối thoại. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-14.mp3',
    language: 'Vietnamese',
    gender: 'Male',
    tags: ['Vietnamese', 'Male', 'AI Dancing', 'Voice Clone', 'Thoải mái', 'Đối thoại'],
  },
  {
    id: 'aidancing_15',
    voiceIndex: '15',
    label: 'Tuấn - Thân thiện, Điềm tĩnh',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Tuấn - Thân thiện, Điềm tĩnh. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-15.mp3',
    language: 'Vietnamese',
    gender: 'Male',
    tags: ['Vietnamese', 'Male', 'AI Dancing', 'Voice Clone', 'Thân thiện', 'Điềm tĩnh'],
  },
  {
    id: 'aidancing_16',
    voiceIndex: '16',
    label: 'Nhật',
    description: 'Giọng đọc Tiếng Việt AI Dancing Nhật. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-16.mp3',
    language: 'Vietnamese',
    gender: 'Male',
    tags: ['Vietnamese', 'Male', 'AI Dancing', 'Voice Clone'],
  },
  {
    id: 'aidancing_17',
    voiceIndex: '17',
    label: 'Huyền - Điềm tĩnh, Thân thiện',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Huyền - Điềm tĩnh, Thân thiện. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-17.mp3',
    language: 'Vietnamese',
    gender: 'Male',
    tags: ['Vietnamese', 'Male', 'AI Dancing', 'Voice Clone', 'Điềm tĩnh', 'Thân thiện'],
  },
  {
    id: 'aidancing_18',
    voiceIndex: '18',
    label: 'Trung - Nhẹ nhàng, Mượt mà',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Trung - Nhẹ nhàng, Mượt mà. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-18.mp3',
    language: 'Vietnamese',
    gender: 'Male',
    tags: ['Vietnamese', 'Male', 'AI Dancing', 'Voice Clone', 'Nhẹ nhàng', 'Mượt mà'],
  },
  {
    id: 'aidancing_19',
    voiceIndex: '19',
    label: 'Đức - Rõ ràng, Điềm tĩnh',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Đức - Rõ ràng, Điềm tĩnh. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-19.mp3',
    language: 'Vietnamese',
    gender: 'Male',
    tags: ['Vietnamese', 'Male', 'AI Dancing', 'Voice Clone', 'Rõ ràng', 'Điềm tĩnh'],
  },
  {
    id: 'aidancing_20',
    voiceIndex: '20',
    label: 'Quang Nguyễn - Ấm áp, Sôi nổi',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Quang Nguyễn - Ấm áp, Sôi nổi. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-20.mp3',
    language: 'Vietnamese',
    gender: 'Male',
    tags: ['Vietnamese', 'Male', 'AI Dancing', 'Voice Clone', 'Ấm áp', 'Sôi nổi'],
  },
  {
    id: 'aidancing_21',
    voiceIndex: '21',
    label: 'Ly - Rõ ràng, Điềm tĩnh',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Ly - Rõ ràng, Điềm tĩnh. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-21.mp3',
    language: 'Vietnamese',
    gender: 'Female',
    tags: ['Vietnamese', 'Female', 'AI Dancing', 'Voice Clone', 'Rõ ràng', 'Điềm tĩnh'],
  },
  {
    id: 'aidancing_22',
    voiceIndex: '22',
    label: 'Trang - Rõ ràng, Mượt mà',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Trang - Rõ ràng, Mượt mà. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-22.mp3',
    language: 'Vietnamese',
    gender: 'Female',
    tags: ['Vietnamese', 'Female', 'AI Dancing', 'Voice Clone', 'Rõ ràng', 'Mượt mà'],
  },
  {
    id: 'aidancing_23',
    voiceIndex: '23',
    label: 'Hùng Trần - Trầm, Điềm tĩnh',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Hùng Trần - Trầm, Điềm tĩnh. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-23.mp3',
    language: 'Vietnamese',
    gender: 'Male',
    tags: ['Vietnamese', 'Male', 'AI Dancing', 'Voice Clone', 'Trầm', 'Điềm tĩnh'],
  },
  {
    id: 'aidancing_24',
    voiceIndex: '24',
    label: 'Kênh',
    description: 'Giọng đọc Tiếng Việt AI Dancing Kênh. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-24.mp3',
    language: 'Vietnamese',
    gender: 'Female',
    tags: ['Vietnamese', 'Female', 'AI Dancing', 'Voice Clone'],
  },
  {
    id: 'aidancing_25',
    voiceIndex: '25',
    label: 'Anh - Ấm áp, Điềm tĩnh',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Anh - Ấm áp, Điềm tĩnh. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-25.mp3',
    language: 'Vietnamese',
    gender: 'Female',
    tags: ['Vietnamese', 'Female', 'AI Dancing', 'Voice Clone', 'Ấm áp', 'Điềm tĩnh'],
  },
  {
    id: 'aidancing_26',
    voiceIndex: '26',
    label: 'Hoàng Đặng - Trầm, Mượt mà',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Hoàng Đặng - Trầm, Mượt mà. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-26.mp3',
    language: 'Vietnamese',
    gender: 'Female',
    tags: ['Vietnamese', 'Female', 'AI Dancing', 'Voice Clone', 'Trầm', 'Mượt mà'],
  },
  {
    id: 'aidancing_27',
    voiceIndex: '27',
    label: 'Viên - Ấm áp, Rõ ràng',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Viên - Ấm áp, Rõ ràng. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-27.mp3',
    language: 'Vietnamese',
    gender: 'Male',
    tags: ['Vietnamese', 'Male', 'AI Dancing', 'Voice Clone', 'Ấm áp', 'Rõ ràng'],
  },
  {
    id: 'aidancing_28',
    voiceIndex: '28',
    label: 'Ngân - Rộn ràng',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Ngân - Rộn ràng. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-28.mp3',
    language: 'Vietnamese',
    gender: 'Female',
    tags: ['Vietnamese', 'Female', 'AI Dancing', 'Voice Clone', 'Rộn ràng'],
  },
  {
    id: 'aidancing_29',
    voiceIndex: '29',
    label: 'Dũng - Trầm, Vang vọng',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Dũng - Trầm, Vang vọng. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-29.mp3',
    language: 'Vietnamese',
    gender: 'Male',
    tags: ['Vietnamese', 'Male', 'AI Dancing', 'Voice Clone', 'Trầm', 'Vang vọng'],
  },
  {
    id: 'aidancing_30',
    voiceIndex: '30',
    label: 'Sang Trương - Trầm, Điềm tĩnh',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Sang Trương - Trầm, Điềm tĩnh. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-30.mp3',
    language: 'Vietnamese',
    gender: 'Male',
    tags: ['Vietnamese', 'Male', 'AI Dancing', 'Voice Clone', 'Trầm', 'Điềm tĩnh'],
  },
  {
    id: 'aidancing_31',
    voiceIndex: '31',
    label: 'Huyền - Rõ ràng, Tự tin',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Huyền - Rõ ràng, Tự tin. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-31.mp3',
    language: 'Vietnamese',
    gender: 'Male',
    tags: ['Vietnamese', 'Male', 'AI Dancing', 'Voice Clone', 'Rõ ràng', 'Tự tin'],
  },
  {
    id: 'aidancing_32',
    voiceIndex: '32',
    label: 'Thắm',
    description: 'Giọng đọc Tiếng Việt AI Dancing Thắm. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-32.mp3',
    language: 'Vietnamese',
    gender: 'Female',
    tags: ['Vietnamese', 'Female', 'AI Dancing', 'Voice Clone'],
  },
  {
    id: 'aidancing_33',
    voiceIndex: '33',
    label: 'Thảo - Nhẹ nhàng, Điềm tĩnh',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Thảo - Nhẹ nhàng, Điềm tĩnh. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-33.mp3',
    language: 'Vietnamese',
    gender: 'Female',
    tags: ['Vietnamese', 'Female', 'AI Dancing', 'Voice Clone', 'Nhẹ nhàng', 'Điềm tĩnh'],
  },
  {
    id: 'aidancing_34',
    voiceIndex: '34',
    label: 'Hào - Ấm áp, Dịu dàng',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Hào - Ấm áp, Dịu dàng. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-34.mp3',
    language: 'Vietnamese',
    gender: 'Male',
    tags: ['Vietnamese', 'Male', 'AI Dancing', 'Voice Clone', 'Ấm áp', 'Dịu dàng'],
  },
  {
    id: 'aidancing_35',
    voiceIndex: '35',
    label: 'My - Nhẹ nhàng, Ấm áp',
    description:
      'Giọng đọc Tiếng Việt AI Dancing My - Nhẹ nhàng, Ấm áp. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-35.mp3',
    language: 'Vietnamese',
    gender: 'Female',
    tags: ['Vietnamese', 'Female', 'AI Dancing', 'Voice Clone', 'Nhẹ nhàng', 'Ấm áp'],
  },
  {
    id: 'aidancing_36',
    voiceIndex: '36',
    label: 'Liam - Ấm áp',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Liam - Ấm áp. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-36.mp3',
    language: 'Vietnamese',
    gender: 'Male',
    tags: ['Vietnamese', 'Male', 'AI Dancing', 'Voice Clone', 'Ấm áp'],
  },
  {
    id: 'aidancing_37',
    voiceIndex: '37',
    label: 'Thanh - Rõ ràng, Ổn định',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Thanh - Rõ ràng, Ổn định. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-37.mp3',
    language: 'Vietnamese',
    gender: 'Female',
    tags: ['Vietnamese', 'Female', 'AI Dancing', 'Voice Clone', 'Rõ ràng', 'Ổn định'],
  },
  {
    id: 'aidancing_38',
    voiceIndex: '38',
    label: 'Giang - Ấm áp, Tự tin',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Giang - Ấm áp, Tự tin. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-38.mp3',
    language: 'Vietnamese',
    gender: 'Female',
    tags: ['Vietnamese', 'Female', 'AI Dancing', 'Voice Clone', 'Ấm áp', 'Tự tin'],
  },
  {
    id: 'aidancing_39',
    voiceIndex: '39',
    label: 'Huy Lê - Điềm tĩnh, Rõ ràng',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Huy Lê - Điềm tĩnh, Rõ ràng. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-39.mp3',
    language: 'Vietnamese',
    gender: 'Male',
    tags: ['Vietnamese', 'Male', 'AI Dancing', 'Voice Clone', 'Điềm tĩnh', 'Rõ ràng'],
  },
  {
    id: 'aidancing_40',
    voiceIndex: '40',
    label: 'Huỳnh Dương - Năng động, Tự tin',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Huỳnh Dương - Năng động, Tự tin. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-40.mp3',
    language: 'Vietnamese',
    gender: 'Male',
    tags: ['Vietnamese', 'Male', 'AI Dancing', 'Voice Clone', 'Năng động', 'Tự tin'],
  },
  {
    id: 'aidancing_41',
    voiceIndex: '41',
    label: 'Phương - Mượt mà, An ủi',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Phương - Mượt mà, An ủi. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-41.mp3',
    language: 'Vietnamese',
    gender: 'Female',
    tags: ['Vietnamese', 'Female', 'AI Dancing', 'Voice Clone', 'Mượt mà', 'An ủi'],
  },
  {
    id: 'aidancing_42',
    voiceIndex: '42',
    label: 'Minh - Rõ ràng, Chắc chắn',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Minh - Rõ ràng, Chắc chắn. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-42.mp3',
    language: 'Vietnamese',
    gender: 'Male',
    tags: ['Vietnamese', 'Male', 'AI Dancing', 'Voice Clone', 'Rõ ràng', 'Chắc chắn'],
  },
  {
    id: 'aidancing_43',
    voiceIndex: '43',
    label: 'An Nhiên',
    description: 'Giọng đọc Tiếng Việt AI Dancing An Nhiên. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-43.mp3',
    language: 'Vietnamese',
    gender: 'Female',
    tags: ['Vietnamese', 'Female', 'AI Dancing', 'Voice Clone'],
  },
  {
    id: 'aidancing_44',
    voiceIndex: '44',
    label: 'Xuân - Năng động',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Xuân - Năng động. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-44.mp3',
    language: 'Vietnamese',
    gender: 'Female',
    tags: ['Vietnamese', 'Female', 'AI Dancing', 'Voice Clone', 'Năng động'],
  },
  {
    id: 'aidancing_45',
    voiceIndex: '45',
    label: 'Quỳnh Anh',
    description: 'Giọng đọc Tiếng Việt AI Dancing Quỳnh Anh. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-45.mp3',
    language: 'Vietnamese',
    gender: 'Female',
    tags: ['Vietnamese', 'Female', 'AI Dancing', 'Voice Clone'],
  },
  {
    id: 'aidancing_46',
    voiceIndex: '46',
    label: 'Emma - Điềm tĩnh, Êm dịu',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Emma - Điềm tĩnh, Êm dịu. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-46.mp3',
    language: 'Vietnamese',
    gender: 'Female',
    tags: ['Vietnamese', 'Female', 'AI Dancing', 'Voice Clone', 'Điềm tĩnh', 'Êm dịu'],
  },
  {
    id: 'aidancing_47',
    voiceIndex: '47',
    label: 'Phong - Ấm áp, Rõ ràng',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Phong - Ấm áp, Rõ ràng. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-47.mp3',
    language: 'Vietnamese',
    gender: 'Male',
    tags: ['Vietnamese', 'Male', 'AI Dancing', 'Voice Clone', 'Ấm áp', 'Rõ ràng'],
  },
  {
    id: 'aidancing_48',
    voiceIndex: '48',
    label: 'Nhung - Rõ ràng, Trang trọng',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Nhung - Rõ ràng, Trang trọng. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-48.mp3',
    language: 'Vietnamese',
    gender: 'Female',
    tags: ['Vietnamese', 'Female', 'AI Dancing', 'Voice Clone', 'Rõ ràng', 'Trang trọng'],
  },
  {
    id: 'aidancing_49',
    voiceIndex: '49',
    label: 'Trang - Nhẹ nhàng',
    description:
      'Giọng đọc Tiếng Việt AI Dancing Trang - Nhẹ nhàng. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-49.mp3',
    language: 'Vietnamese',
    gender: 'Female',
    tags: ['Vietnamese', 'Female', 'AI Dancing', 'Voice Clone', 'Nhẹ nhàng'],
  },
  {
    id: 'aidancing_50',
    voiceIndex: '50',
    label: 'Viết Linh',
    description: 'Giọng đọc Tiếng Việt AI Dancing Viết Linh. Hỗ trợ đọc trực tiếp và Clone giọng.',
    previewUrl: 'https://video.aidancing.net/audio/voice-vi-50.mp3',
    language: 'Vietnamese',
    gender: 'Male',
    tags: ['Vietnamese', 'Male', 'AI Dancing', 'Voice Clone'],
  },
]
