import type { TitleScene, TitleTemplateItem, TitleMode } from '../types'

export const BASE_SCENE: TitleScene = {
  mode: 'message',
  text: '',
  subText: '',
  subPosition: 'below',
  width: 1280,
  height: 720,
  sizePreset: '1280x720',
  anchor: 'mc',
  marginX: 64,
  marginY: 56,
  offsetX: 0,
  offsetY: 0,
  writing: 'h',
  align: 'center',
  autoFit: true,
  wrapChars: 0,
  fontId: 'Inter',
  weight: 700,
  italic: false,
  fontSize: 120,
  letterSpacing: 0.08,
  lineHeight: 1.5,
  subFontId: 'same',
  subWeight: 400,
  subItalic: false,
  subSize: 0.3,
  subLetterSpacing: 0.25,
  subGap: 0.3,
  fill: { type: 'solid', color: '#ffffff', color2: '#ffd76a', color3: '', dir: 'v' },
  fillOpacity: 1,
  stroke: { on: true, width: 5, color: '#1b1b1f' },
  stroke2: { on: false, width: 6, color: '#ffffff' },
  shadow: { on: true, color: '#000000', opacity: 0.6, blur: 12, x: 0, y: 5 },
  glow: { on: false, color: '#7fb4ff', size: 28, strength: 1 },
  subColorOn: false,
  subColor: '#ffffff',
  deco: {
    type: 'none',
    color: '#000000',
    opacity: 0.55,
    color2: '#ffffff',
    pad: 0.4,
    extend: 0.8,
    thickness: 3,
    outline: false,
    soft: 0.5,
    sideFade: 0.3,
    radius: 0.2,
    anim: 'grow',
    dur: 0.45,
    tapeColor: '#f5c400',
    tapeStripe: '#151515',
    tapeSize: 40,
    tapeSpeed: 90,
    tapeBlink: 0.5,
  },
  bg: { type: 'none', color: '#000000', opacity: 0.45, sync: true },
  inFx: 'fade',
  inDur: 0.6,
  inStagger: 0,
  inOrder: 'forward',
  inEase: 'auto',
  inPower: 1,
  inDir: 'left',
  holdFx: 'none',
  hold: 1.5,
  holdPower: 1,
  glitchColor: '#ff285a',
  glitchColor2: '#28e6ff',
  inEnabled: true,
  outEnabled: true,
  outFx: 'fade',
  outDur: 0.6,
  outStagger: 0,
  outOrder: 'forward',
  outEase: 'auto',
  outPower: 1,
  outDir: 'left',
  subFx: 'same',
  subDelay: -0.2,
  startDelay: 0.1,
  endDelay: 0.3,
  reveal: 'char',
  cps: 12,
  glyphDur: 0.4,
  linePause: 0.35,
  punctPause: 0.25,
  lineInterval: 0.9,
  sweepDur: 1.2,
  pageSplit: true,
  pageGap: 0.3,
  cursor: false,
  cursorColor: '',
  scrollSpeed: 90,
  scrollFade: true,
  soloSize: 0.55,
  soloPause: 0.4,
  soloImpact: 1,
  spreadHold: 0.5,
  spreadDur: 0.9,
}

export const MODE_DEFAULTS: Record<TitleMode, Partial<TitleScene>> = {
  message: { mode: 'message', fontSize: 130 },
  trailer: { mode: 'trailer', fontSize: 46, lineHeight: 1.9, subText: '' },
  caption: { mode: 'caption', fontSize: 110 },
}

export const TEMPLATES: Record<TitleMode, TitleTemplateItem[]> = {
  caption: [
    {
      id: 'converge',
      icon: 'converge',
      label: { vi: 'Hội tụ trên dưới', en: 'Converge', ja: '上下から合流' },
      text: { vi: 'PHÒNG Y TẾ', en: 'Infirmary', ja: '保健室' },
      subText: { vi: 'Sau giờ học — 16:30', en: 'After School — 4:30 PM', ja: '放課後 16:30' },
      patch: {
        fontId: 'Inter',
        weight: 800,
        fontSize: 110,
        letterSpacing: 0.2,
        subFontId: 'same',
        subWeight: 400,
        subSize: 0.3,
        subLetterSpacing: 0.2,
        subGap: 0.35,
        fill: { type: 'solid', color: '#ffffff' },
        stroke: { on: false, width: 0, color: '#000000' },
        stroke2: { on: false, width: 0, color: '#ffffff' },
        shadow: { on: true, color: '#000000', opacity: 0.85, blur: 14, x: 0, y: 4 },
        deco: {
          type: 'sides',
          color2: '#ffffff',
          pad: 0.45,
          extend: 1.2,
          thickness: 2,
          anim: 'grow',
          dur: 0.7,
        },
        inFx: 'converge',
        inDur: 0.9,
        inStagger: 0.12,
        hold: 1.6,
        outFx: 'fade',
        outDur: 0.7,
        subFx: 'fade',
        subDelay: -0.3,
      },
    },
    {
      id: 'float',
      icon: 'floatUp',
      label: { vi: 'Bay lượn nhẹ', en: 'Float Up', ja: '浮かび上がる' },
      text: { vi: 'TẦNG 3 KHU CŨ', en: 'Old Building, 3F', ja: '旧校舎 三階' },
      subText: { vi: '19:45 TỐI', en: '7:45 PM', ja: 'PM 7:45' },
      patch: {
        fontId: 'Inter',
        weight: 800,
        fontSize: 96,
        letterSpacing: 0.14,
        subFontId: 'same',
        subWeight: 400,
        subSize: 0.32,
        subLetterSpacing: 0.3,
        fill: { type: 'solid', color: '#f2f6ff' },
        stroke: { on: false, width: 0, color: '#000000' },
        stroke2: { on: false, width: 0, color: '#ffffff' },
        shadow: { on: true, color: '#000000', opacity: 0.8, blur: 14, x: 0, y: 4 },
        glow: { on: true, color: '#9cc2ff', size: 22, strength: 0.6 },
        inFx: 'rise',
        inDur: 1.0,
        inStagger: 0.07,
        hold: 1.6,
        outFx: 'rise',
        outDur: 0.8,
        outStagger: 0.04,
        subFx: 'fade',
      },
    },
    {
      id: 'cinema',
      icon: 'spacing',
      label: { vi: 'Điện ảnh tracking', en: 'Cinematic Tracking', ja: '字間シネマ' },
      text: { vi: 'TOKYO', en: 'TOKYO', ja: 'TOKYO' },
      subText: { vi: '2026.10.31 23:59', en: '2026.10.31 23:59', ja: '2026.10.31 23:59' },
      patch: {
        fontId: 'Cinzel',
        weight: 700,
        fontSize: 120,
        letterSpacing: 0.45,
        subFontId: 'same',
        subWeight: 400,
        subSize: 0.22,
        subLetterSpacing: 0.6,
        fill: { type: 'solid', color: '#ffffff' },
        stroke: { on: false, width: 0, color: '#000000' },
        stroke2: { on: false, width: 0, color: '#ffffff' },
        shadow: { on: true, color: '#000000', opacity: 0.7, blur: 14, x: 0, y: 4 },
        glow: { on: true, color: '#ffffff', size: 20, strength: 0.35 },
        inFx: 'tracking',
        inDur: 1.6,
        hold: 1.4,
        outFx: 'tracking',
        outDur: 1.2,
        subFx: 'fade',
        subDelay: -0.6,
      },
    },
    {
      id: 'clock',
      icon: 'stopwatch',
      label: { vi: 'Mốc thời gian', en: 'Time Stamp', ja: '時刻表示' },
      text: { vi: '23:59', en: '23:59', ja: '23:59' },
      subText: { vi: '2026.10.31 SAT', en: '2026.10.31 SAT', ja: '2026.10.31 SAT' },
      patch: {
        fontId: 'Orbitron',
        weight: 700,
        fontSize: 130,
        letterSpacing: 0.12,
        subFontId: 'same',
        subWeight: 400,
        subSize: 0.2,
        subLetterSpacing: 0.4,
        fill: { type: 'solid', color: '#dff9ff' },
        stroke: { on: false, width: 0, color: '#000000' },
        stroke2: { on: false, width: 0, color: '#ffffff' },
        shadow: { on: false, color: '#000000', opacity: 0, blur: 0, x: 0, y: 0 },
        glow: { on: true, color: '#3ad7ff', size: 30, strength: 1 },
        deco: {
          type: 'corners',
          color2: '#8feaff',
          pad: 0.4,
          thickness: 3,
          anim: 'grow',
          dur: 0.5,
        },
        inFx: 'flicker',
        inDur: 0.8,
        inStagger: 0.05,
        hold: 2,
        outFx: 'flicker',
        outDur: 0.6,
        subFx: 'fade',
      },
    },
    {
      id: 'underline',
      icon: 'underline',
      label: {
        vi: 'Gạch chân (Dưới trái)',
        en: 'Underline (Bottom Left)',
        ja: '下線スライド（左下）',
      },
      text: { vi: 'THƯ VIỆN TRUNG TÂM', en: 'Library', ja: '図書室' },
      subText: { vi: '17:12 CHIỀU', en: '5:12 PM', ja: '午後 5時12分' },
      patch: {
        anchor: 'bl',
        align: 'start',
        marginX: 72,
        marginY: 64,
        fontId: 'Inter',
        weight: 900,
        fontSize: 84,
        letterSpacing: 0.12,
        subFontId: 'same',
        subWeight: 400,
        subSize: 0.36,
        subLetterSpacing: 0.15,
        subGap: 0.45,
        fill: { type: 'solid', color: '#ffffff' },
        stroke: { on: false, width: 0, color: '#000000' },
        stroke2: { on: false, width: 0, color: '#ffffff' },
        shadow: { on: true, color: '#000000', opacity: 0.8, blur: 10, x: 0, y: 3 },
        deco: {
          type: 'underline',
          color2: '#ffffff',
          pad: 0.2,
          extend: 0.3,
          thickness: 3,
          anim: 'grow',
          dur: 0.7,
        },
        inFx: 'slide',
        inDir: 'left',
        inDur: 0.7,
        inStagger: 0.05,
        hold: 1.8,
        outFx: 'fade',
        outDur: 0.6,
        subFx: 'fade',
      },
    },
    {
      id: 'vertical',
      icon: 'vertical',
      label: { vi: 'Dọc (Trên phải)', en: 'Vertical (Top Right)', ja: '縦書き（右上）' },
      text: { vi: 'ĐỀN THỜ CỔ', en: 'Shrine Grounds', ja: '神社の境内' },
      subText: { vi: '02:00 ĐÊM', en: '2:00 AM', ja: '深夜 二時' },
      patch: {
        writing: 'v',
        anchor: 'tr',
        align: 'start',
        marginX: 72,
        marginY: 56,
        fontId: 'Cinzel',
        weight: 800,
        fontSize: 90,
        letterSpacing: 0.1,
        subFontId: 'same',
        subWeight: 400,
        subSize: 0.36,
        subLetterSpacing: 0.15,
        subGap: 0.35,
        fill: { type: 'solid', color: '#f4f1ea' },
        stroke: { on: false, width: 0, color: '#000000' },
        stroke2: { on: false, width: 0, color: '#ffffff' },
        shadow: { on: true, color: '#000000', opacity: 0.85, blur: 12, x: 0, y: 3 },
        deco: {
          type: 'bar',
          color2: '#c9a24a',
          pad: 0.35,
          thickness: 3,
          anim: 'grow',
          dur: 0.6,
        },
        inFx: 'converge',
        inDur: 0.9,
        inStagger: 0.1,
        hold: 1.8,
        outFx: 'fade',
        outDur: 0.7,
        subFx: 'fade',
      },
    },
    {
      id: 'boxed',
      icon: 'frame',
      label: { vi: 'Hộp bo góc (Trên trái)', en: 'Boxed (Top Left)', ja: 'ボックス（左上）' },
      text: { vi: 'Research Wing B1', en: 'Research Wing B1', ja: '第三研究棟 地下' },
      subText: {
        vi: 'B1F — Restricted Area',
        en: 'B1F — Restricted Area',
        ja: 'B1F ― 立入禁止区域',
      },
      patch: {
        anchor: 'tl',
        align: 'start',
        marginX: 56,
        marginY: 48,
        fontId: 'Inter',
        weight: 700,
        fontSize: 64,
        letterSpacing: 0.08,
        subFontId: 'same',
        subWeight: 400,
        subSize: 0.42,
        subLetterSpacing: 0.12,
        subGap: 0.3,
        fill: { type: 'solid', color: '#ffffff' },
        stroke: { on: false, width: 0, color: '#000000' },
        stroke2: { on: false, width: 0, color: '#ffffff' },
        shadow: { on: false, color: '#000000', opacity: 0, blur: 0, x: 0, y: 0 },
        deco: {
          type: 'box',
          color: '#05070c',
          opacity: 0.6,
          color2: '#8fd3ff',
          pad: 0.45,
          radius: 0.12,
          thickness: 0,
          anim: 'grow',
          dur: 0.5,
        },
        inFx: 'blurIn',
        inDur: 0.7,
        inStagger: 0.04,
        hold: 1.8,
        outFx: 'fade',
        outDur: 0.6,
        subFx: 'fade',
      },
    },
  ],

  message: [
    {
      id: 'battle',
      group: 'combat',
      icon: 'swords',
      label: { vi: 'Bắt đầu giao chiến', en: 'Battle Start', ja: '戦闘開始' },
      text: { vi: 'CHIẾN ĐẤU BẮT ĐẦU', en: 'BATTLE START', ja: '戦闘開始' },
      subText: { vi: 'ENGAGE — READY', en: 'ENGAGE', ja: 'BATTLE START' },
      patch: {
        fontId: 'Cinzel',
        weight: 800,
        fontSize: 124,
        letterSpacing: 0.12,
        subFontId: 'Cinzel',
        subWeight: 700,
        subSize: 0.2,
        subLetterSpacing: 0.6,
        subGap: 0.62,
        fill: { type: 'solid', color: '#ffffff' },
        stroke: { on: false, width: 0, color: '#000000' },
        stroke2: { on: false, width: 0, color: '#ffffff' },
        shadow: { on: true, color: '#000000', opacity: 0.35, blur: 10, x: 0, y: 3 },
        glow: { on: false, color: '#ffffff', size: 0, strength: 0 },
        deco: {
          type: 'frame',
          color: '#000000',
          opacity: 0,
          color2: '#ffffff',
          thickness: 3,
          pad: 0.28,
          extend: 12,
          anim: 'grow',
          dur: 0.6,
        },
        inFx: 'drop',
        inDur: 0.55,
        inStagger: 0.1,
        inPower: 1.1,
        hold: 1.4,
        outFx: 'zoomThrough',
        outDur: 0.5,
        subFx: 'fade',
        subDelay: -0.1,
      },
    },
    {
      id: 'openCombat',
      group: 'combat',
      icon: 'chip',
      label: { vi: 'Cyber Chiến đấu', en: 'Open Combat', ja: 'OPEN COMBAT' },
      text: { vi: 'OPEN COMBAT', en: 'OPEN COMBAT', ja: 'OPEN COMBAT' },
      subText: { vi: 'COMBAT MODE : ONLINE', en: 'COMBAT MODE : ONLINE', ja: '戦闘開始' },
      patch: {
        fontId: 'Orbitron',
        weight: 900,
        fontSize: 120,
        letterSpacing: 0.16,
        subFontId: 'Inter',
        subWeight: 400,
        subSize: 0.3,
        subLetterSpacing: 0.5,
        subGap: 0.45,
        fill: {
          type: 'gradient',
          color: '#ffffff',
          color2: '#b8f6ff',
          color3: '#3fd8ff',
          dir: 'v',
        },
        stroke: { on: true, width: 1.5, color: '#00e5ff' },
        stroke2: { on: false, width: 0, color: '#ffffff' },
        shadow: { on: false, color: '#000000', opacity: 0, blur: 0, x: 0, y: 0 },
        glow: { on: true, color: '#00d9ff', size: 30, strength: 1.3 },
        subColorOn: true,
        subColor: '#6ff0ff',
        deco: {
          type: 'lines',
          color2: '#00e5ff',
          pad: 0.3,
          extend: 0.6,
          thickness: 2,
          anim: 'grow',
          dur: 0.45,
        },
        inFx: 'glitch',
        inDur: 0.8,
        holdFx: 'glitch',
        holdPower: 0.6,
        hold: 1.8,
        outFx: 'glitch',
        outDur: 0.5,
        subFx: 'typewriter',
        subDelay: -0.1,
      },
    },
    {
      id: 'defeat',
      group: 'combat',
      icon: 'skull',
      label: { vi: 'Thất bại (Defeat)', en: 'Defeat', ja: '敗北' },
      text: { vi: 'THẤT BẠI', en: 'DEFEAT', ja: '敗北' },
      subText: { vi: 'BATTLE LOST', en: 'BATTLE LOST', ja: 'DEFEAT' },
      patch: {
        fontId: 'Cinzel',
        weight: 800,
        fontSize: 150,
        letterSpacing: 0.3,
        subFontId: 'Cinzel',
        subWeight: 700,
        subSize: 0.2,
        subLetterSpacing: 0.9,
        subGap: 0.45,
        fill: {
          type: 'gradient',
          color: '#ff7070',
          color2: '#e41414',
          color3: '#780000',
          dir: 'v',
        },
        stroke: { on: true, width: 2, color: '#000000' },
        stroke2: { on: false, width: 0, color: '#ffffff' },
        shadow: { on: true, color: '#000000', opacity: 0.9, blur: 14, x: 0, y: 5 },
        glow: { on: true, color: '#c80000', size: 30, strength: 1 },
        subColorOn: true,
        subColor: '#e03a3a',
        deco: {
          type: 'band',
          color: '#000000',
          opacity: 0.88,
          pad: 0.42,
          soft: 0.25,
          sideFade: 0.35,
          anim: 'grow',
          dur: 0.35,
        },
        glitchColor: '#ff2020',
        glitchColor2: '#000000',
        inFx: 'glitch',
        inDur: 0.9,
        holdFx: 'glitch',
        holdPower: 1,
        hold: 1.8,
        outFx: 'glitch',
        outDur: 0.8,
        subFx: 'fade',
        subDelay: -0.2,
      },
    },
    {
      id: 'emergency',
      group: 'investigation',
      icon: 'warning',
      label: { vi: 'Khẩn cấp (Tape)', en: 'Emergency', ja: '緊急事態' },
      text: { vi: 'KHẨN CẤP', en: 'EMERGENCY', ja: '緊急事態' },
      subText: { vi: 'WARNING — CODE RED', en: 'WARNING', ja: 'EMERGENCY' },
      patch: {
        fontId: 'Oswald',
        weight: 900,
        fontSize: 118,
        letterSpacing: 0.32,
        subFontId: 'Oswald',
        subWeight: 700,
        subSize: 0.26,
        subLetterSpacing: 0.7,
        subGap: 0.32,
        fill: { type: 'solid', color: '#ffffff' },
        stroke: { on: true, width: 4, color: '#8a0000' },
        stroke2: { on: false, width: 0, color: '#ffffff' },
        shadow: { on: true, color: '#000000', opacity: 0.65, blur: 8, x: 0, y: 3 },
        glow: { on: false, color: '#000000', size: 0, strength: 0 },
        subColorOn: true,
        subColor: '#f5c400',
        deco: {
          type: 'tape',
          pad: 0.3,
          anim: 'grow',
          dur: 0.55,
          tapeSize: 54,
          tapeSpeed: 110,
          tapeBlink: 0.55,
        },
        inFx: 'shutter',
        inDir: 'v',
        inDur: 0.45,
        hold: 1.8,
        outFx: 'fade',
        outDur: 0.5,
        subFx: 'fade',
        subDelay: -0.1,
      },
    },
    {
      id: 'chapter',
      group: 'scene',
      icon: 'book',
      label: { vi: 'Tiêu đề chương', en: 'Chapter Title', ja: '章タイトル' },
      text: { vi: 'CHƯƠNG I', en: 'CHAPTER I', ja: '第一章' },
      subText: { vi: '“Đêm Thức Tỉnh”', en: '“The Night of Awakening”', ja: '「目覚めの夜」' },
      patch: {
        fontId: 'Cinzel',
        weight: 800,
        fontSize: 128,
        letterSpacing: 0.22,
        subFontId: 'same',
        subWeight: 400,
        subSize: 0.3,
        subLetterSpacing: 0.15,
        subGap: 0.45,
        fill: { type: 'solid', color: '#ffffff' },
        stroke: { on: false, width: 0, color: '#000000' },
        stroke2: { on: false, width: 0, color: '#ffffff' },
        shadow: { on: true, color: '#000000', opacity: 0.8, blur: 14, x: 0, y: 4 },
        deco: {
          type: 'underline',
          color2: '#ffffff',
          pad: 0.3,
          extend: 0.5,
          thickness: 2,
          anim: 'grow',
          dur: 0.9,
        },
        inFx: 'blurIn',
        inDur: 1.0,
        inStagger: 0.15,
        hold: 1.6,
        outFx: 'fade',
        outDur: 0.8,
        subFx: 'fade',
        subDelay: -0.2,
      },
    },
    {
      id: 'missionClear',
      group: 'investigation',
      icon: 'checkCircle',
      label: { vi: 'Nhiệm vụ hoàn thành', en: 'Mission Clear', ja: 'ミッションクリア' },
      text: { vi: 'MISSION CLEAR', en: 'MISSION CLEAR', ja: 'MISSION CLEAR' },
      subText: {
        vi: 'ALL OBJECTIVES COMPLETE',
        en: 'ALL OBJECTIVES COMPLETE',
        ja: 'ミッションクリア',
      },
      patch: {
        fontId: 'Oswald',
        weight: 700,
        fontSize: 130,
        letterSpacing: 0.12,
        italic: true,
        subFontId: 'Inter',
        subWeight: 700,
        subSize: 0.2,
        subLetterSpacing: 0.6,
        subGap: 0.28,
        subItalic: true,
        fill: { type: 'solid', color: '#ffffff' },
        stroke: { on: false, width: 0, color: '#000000' },
        stroke2: { on: false, width: 0, color: '#ffffff' },
        shadow: { on: false, color: '#000000', opacity: 0, blur: 0, x: 0, y: 0 },
        glow: { on: false, color: '#ffffff', size: 0, strength: 0 },
        subColorOn: true,
        subColor: '#bdbdbd',
        deco: {
          type: 'band',
          color: '#000000',
          opacity: 0.9,
          pad: 0.3,
          soft: 0,
          sideFade: 0,
          anim: 'grow',
          dur: 0.25,
        },
        inFx: 'slide',
        inDir: 'left',
        inDur: 0.35,
        inStagger: 0.03,
        inPower: 2,
        hold: 1.6,
        outFx: 'wipe',
        outDir: 'lr',
        outDur: 0.35,
        subFx: 'fade',
        subDelay: -0.1,
      },
    },
  ],

  trailer: [
    {
      id: 'cinematic',
      icon: 'play',
      label: { vi: 'Điện ảnh mờ ảo', en: 'Cinematic', ja: 'シネマティック' },
      text: {
        vi: 'Khi mọi điều bất khả đã bị loại trừ —\nthì thứ còn lại, dù kỳ dị đến đâu, chính là sự thật.',
        en: 'Eliminate the impossible —\nand whatever remains is not of this world.',
        ja: 'ありえないものを消し去ったとき――\n残ったのは、この世ならざる真実だった。',
      },
      subText: { vi: '', en: '', ja: '' },
      patch: {
        fontId: 'Inter',
        weight: 700,
        fontSize: 46,
        lineHeight: 1.9,
        letterSpacing: 0.08,
        fill: { type: 'solid', color: '#f5f0e6' },
        stroke: { on: false, width: 0, color: '#000000' },
        stroke2: { on: false, width: 0, color: '#ffffff' },
        shadow: { on: true, color: '#000000', opacity: 0.85, blur: 10, x: 0, y: 3 },
        glow: { on: true, color: '#8fb0ff', size: 18, strength: 0.6 },
        bg: { type: 'none' },
        reveal: 'char',
        cps: 12,
        glyphDur: 0.5,
        inFx: 'blurIn',
        hold: 1.6,
        outFx: 'fade',
        outDur: 0.8,
        wrapChars: 26,
        cursor: false,
      },
    },
    {
      id: 'typewriter',
      icon: 'typewriter',
      label: { vi: 'Máy đánh chữ', en: 'Typewriter', ja: 'タイプライター' },
      text: {
        vi: 'VỤ ÁN DINH THỰ SƯƠNG MÙ',
        en: 'THE MISTY MANOR MURDER',
        ja: '霧の館の殺人',
      },
      subText: { vi: '', en: '', ja: '' },
      patch: {
        fontId: 'Inter',
        weight: 400,
        fontSize: 100,
        lineHeight: 1.5,
        letterSpacing: 0.08,
        align: 'center',
        fill: { type: 'solid', color: '#f6f4ee' },
        stroke: { on: true, width: 1, color: '#f6f4ee' },
        stroke2: { on: false, width: 0, color: '#ffffff' },
        shadow: { on: false, color: '#000000', opacity: 0, blur: 0, x: 0, y: 0 },
        glow: { on: false, color: '#ffffff', size: 0, strength: 0 },
        bg: { type: 'solid', color: '#000000', opacity: 0.9, sync: true },
        reveal: 'solo',
        cps: 8,
        soloSize: 0.65,
        soloPause: 0.6,
        soloImpact: 1,
        inFx: 'typewriter',
        wrapChars: 20,
        cursor: false,
        hold: 2.2,
        outFx: 'fade',
        outDur: 0.5,
      },
    },
    {
      id: 'syslog',
      icon: 'terminal',
      label: { vi: 'Hệ thống Log Terminal', en: 'System Log', ja: 'システムログ' },
      text: {
        vi: 'Ngày: 20XX / XX / XX\nHồ sơ số 13\n\nMỗi đêm cùng giờ đó,\ntiếng dương cầm lại vang lên từ căn biệt thự.',
        en: 'Date: 20XX / XX / XX\nInvestigation Log No.13\n\nEvery night at the same hour,\npiano music echoes through the mansion.',
        ja: '20XX年 X月X日\n調査記録 No.13\n\n対象の館では、夜ごと同じ時刻に\nピアノの音が聞こえるという。',
      },
      subText: { vi: '', en: '', ja: '' },
      patch: {
        fontId: 'Orbitron',
        weight: 400,
        fontSize: 38,
        lineHeight: 1.7,
        letterSpacing: 0.06,
        align: 'start',
        fill: { type: 'solid', color: '#d9ffe0' },
        stroke: { on: false, width: 0, color: '#000000' },
        stroke2: { on: false, width: 0, color: '#ffffff' },
        shadow: { on: false, color: '#000000', opacity: 0, blur: 0, x: 0, y: 0 },
        glow: { on: true, color: '#3cff7a', size: 14, strength: 0.7 },
        bg: { type: 'solid', color: '#000000', opacity: 0.7, sync: true },
        reveal: 'char',
        cps: 16,
        glyphDur: 0,
        inFx: 'typewriter',
        cursor: true,
        hold: 1.5,
        outFx: 'fade',
        outDur: 0.5,
        wrapChars: 28,
      },
    },
    {
      id: 'spread',
      icon: 'spreadOut',
      label: { vi: 'Mở từ giữa ra hai bên', en: 'Center Spread', ja: '中央から左右' },
      text: {
        vi: 'Cánh cửa phong ấn, giờ đây chính thức mở ra.',
        en: 'The sealed door now swings open.',
        ja: '閉ざされた扉が、いま開かれる。',
      },
      subText: { vi: '', en: '', ja: '' },
      patch: {
        fontId: 'Cinzel',
        weight: 800,
        fontSize: 64,
        lineHeight: 1.7,
        letterSpacing: 0.14,
        fill: { type: 'solid', color: '#f5efe3' },
        stroke: { on: false, width: 0, color: '#000000' },
        stroke2: { on: false, width: 0, color: '#ffffff' },
        shadow: { on: true, color: '#000000', opacity: 0.85, blur: 12, x: 0, y: 3 },
        glow: { on: true, color: '#ffd9a0', size: 20, strength: 0.5 },
        bg: { type: 'none' },
        reveal: 'spread',
        spreadHold: 0.5,
        spreadDur: 0.9,
        inFx: 'fade',
        hold: 2,
        outFx: 'fade',
        outDur: 0.8,
      },
    },
  ],
}

export const STYLE_PRESETS = [
  {
    id: 'plain',
    label: { vi: 'Trắng viền đen', en: 'White + Outline', ja: '白＋黒縁' },
    patch: {
      fill: { type: 'solid' as const, color: '#ffffff' },
      fillOpacity: 1,
      stroke: { on: true, width: 5, color: '#1b1b1f' },
      stroke2: { on: false, width: 0, color: '#ffffff' },
      shadow: { on: true, color: '#000000', opacity: 0.6, blur: 12, x: 0, y: 5 },
      glow: { on: false, color: '#ffffff', size: 0, strength: 0 },
    },
  },
  {
    id: 'gold',
    label: { vi: 'Hoàng Kim', en: 'Gold', ja: '金' },
    patch: {
      fill: {
        type: 'gradient' as const,
        color: '#fffbe6',
        color2: '#ffd257',
        color3: '#b8860b',
        dir: 'v' as const,
      },
      fillOpacity: 1,
      stroke: { on: true, width: 4, color: '#3b2500' },
      stroke2: { on: true, width: 5, color: '#fff3c4' },
      shadow: { on: true, color: '#000000', opacity: 0.6, blur: 14, x: 0, y: 6 },
      glow: { on: true, color: '#ffd257', size: 34, strength: 1 },
    },
  },
  {
    id: 'silver',
    label: { vi: 'Bạch Ngân', en: 'Silver', ja: '銀' },
    patch: {
      fill: {
        type: 'gradient' as const,
        color: '#ffffff',
        color2: '#dfe6ee',
        color3: '#8f9cab',
        dir: 'v' as const,
      },
      fillOpacity: 1,
      stroke: { on: true, width: 3, color: '#1d2430' },
      stroke2: { on: false, width: 0, color: '#ffffff' },
      shadow: { on: true, color: '#000000', opacity: 0.6, blur: 12, x: 0, y: 4 },
      glow: { on: true, color: '#bcd7ff', size: 22, strength: 0.8 },
    },
  },
  {
    id: 'blood',
    label: { vi: 'Đỏ Huyết', en: 'Blood', ja: '血' },
    patch: {
      fill: {
        type: 'gradient' as const,
        color: '#ff6a6a',
        color2: '#b30000',
        color3: '#4a0000',
        dir: 'v' as const,
      },
      fillOpacity: 1,
      stroke: { on: true, width: 3, color: '#1a0000' },
      stroke2: { on: false, width: 0, color: '#ffffff' },
      shadow: { on: true, color: '#000000', opacity: 0.85, blur: 20, x: 0, y: 6 },
      glow: { on: true, color: '#ff1a1a', size: 40, strength: 1.1 },
    },
  },
  {
    id: 'neon',
    label: { vi: 'Cyber Neon', en: 'Neon', ja: 'ネオン' },
    patch: {
      fill: { type: 'solid' as const, color: '#f4fdff' },
      fillOpacity: 1,
      stroke: { on: true, width: 2, color: '#00c8ff' },
      stroke2: { on: false, width: 0, color: '#ffffff' },
      shadow: { on: false, color: '#000000', opacity: 0, blur: 0, x: 0, y: 0 },
      glow: { on: true, color: '#00d9ff', size: 34, strength: 1.6 },
    },
  },
  {
    id: 'pop',
    label: { vi: 'Hoạt hình Pop', en: 'Pop', ja: 'ポップ' },
    patch: {
      fill: {
        type: 'gradient' as const,
        color: '#fffbd1',
        color2: '#ffe14d',
        color3: '#ff9d00',
        dir: 'v' as const,
      },
      fillOpacity: 1,
      stroke: { on: true, width: 7, color: '#6a2c00' },
      stroke2: { on: true, width: 6, color: '#ffffff' },
      shadow: { on: true, color: '#000000', opacity: 0.5, blur: 8, x: 0, y: 6 },
      glow: { on: false, color: '#ffffff', size: 0, strength: 0 },
    },
  },
]

export const SIZE_PRESETS = [
  { id: '1920x1080', w: 1920, h: 1080, label: '1920 × 1080 (16:9 FHD)' },
  { id: '1280x720', w: 1280, h: 720, label: '1280 × 720 (16:9 HD)' },
  { id: '1080x1080', w: 1080, h: 1080, label: '1080 × 1080 (1:1 Vuông)' },
  { id: '720x1280', w: 720, h: 1280, label: '720 × 1280 (9:16 Shorts/TikTok)' },
  { id: '1280x360', w: 1280, h: 360, label: '1280 × 360 (Dải băng ngang)' },
  { id: '1024x256', w: 1024, h: 256, label: '1024 × 256 (Caption Strip)' },
]

export function cloneScene<T>(value: T): T {
  return JSON.parse(JSON.stringify(value))
}

function isPlainObject(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v)
}

export function deepMerge<T extends object>(target: T, patch: Record<string, unknown>): T {
  const targetObj = target as Record<string, unknown>
  Object.keys(patch || {}).forEach((key) => {
    const value = patch[key]
    const targetVal = targetObj[key]
    if (isPlainObject(value) && isPlainObject(targetVal)) {
      deepMerge(targetVal as Record<string, unknown>, value as Record<string, unknown>)
    } else if (value !== undefined) {
      targetObj[key] = cloneScene(value)
    }
  })
  return target
}

export function applyTemplateToScene(
  currentScene: TitleScene,
  template: TitleTemplateItem,
  lang: 'vi' | 'en' | 'ja' = 'vi',
): TitleScene {
  const keep = {
    width: currentScene.width,
    height: currentScene.height,
    sizePreset: currentScene.sizePreset,
    inEnabled: currentScene.inEnabled,
    outEnabled: currentScene.outEnabled,
  }

  const base = deepMerge(
    cloneScene(BASE_SCENE),
    (MODE_DEFAULTS[currentScene.mode] || {}) as Record<string, unknown>,
  )
  const merged = deepMerge(base, template.patch as Record<string, unknown>)

  merged.width = keep.width || merged.width
  merged.height = keep.height || merged.height
  merged.sizePreset = keep.sizePreset || merged.sizePreset
  merged.templateId = template.id

  if (!('outEnabled' in template.patch)) merged.outEnabled = keep.outEnabled !== false
  if (!('inEnabled' in template.patch)) merged.inEnabled = keep.inEnabled !== false

  const textVal = template.text[lang] || template.text.en || template.text.vi
  const subTextVal = template.subText[lang] || template.subText.en || template.subText.vi

  merged.text = textVal
  merged.subText = subTextVal

  return merged
}
