import type { CSSProperties } from 'react'
import type { TextItem } from '@/types/timeline'

export type TextEffectCategory =
  | 'all'
  | 'glow'
  | '3d'
  | 'chrome'
  | 'outline'
  | 'gradient'
  | 'aesthetic'

export interface TextEffectCategoryOption {
  id: TextEffectCategory
  label: string
}

export const TEXT_EFFECT_CATEGORIES: readonly TextEffectCategoryOption[] = [
  { id: 'all', label: 'All' },
  { id: 'glow', label: 'Luminous' },
  { id: '3d', label: '3D & Pop' },
  { id: 'chrome', label: 'Metallic' },
  { id: 'outline', label: 'Outline' },
  { id: 'gradient', label: 'Gradient' },
  { id: 'aesthetic', label: 'Aesthetic' },
] as const

export interface TextEffectItem {
  id: string
  label: string
  category: Exclude<TextEffectCategory, 'all'>
  previewText?: string
  patch: Pick<TextItem, 'color' | 'fontFamily' | 'fontWeight'> &
    Partial<
      Pick<
        TextItem,
        'stroke' | 'textShadow' | 'backgroundColor' | 'backgroundRadius' | 'letterSpacing'
      >
    >
  previewStyle: CSSProperties
}

export const TEXT_EFFECTS_CATALOG: readonly TextEffectItem[] = [
  {
    id: 'cyber-cyan',
    label: 'Cyber Cyan',
    category: 'glow',
    previewText: 'CYBER',
    patch: {
      color: '#ffffff',
      fontFamily: 'Orbitron',
      fontWeight: 'bold',
      stroke: {
        width: 1.5,
        color: '#00e5ff',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 0,
        blur: 24,
        color: '#00e5ff',
      },
      letterSpacing: 3,
    },
    previewStyle: {
      color: '#ffffff',
      fontFamily: 'Orbitron, sans-serif',
      WebkitTextStroke: '1.5px #00e5ff',
      textShadow: '0 0 8px #00e5ff, 0 0 20px #00e5ff, 0 0 35px #0088ff',
      letterSpacing: '2px',
    },
  },
  {
    id: 'tokyo-pink',
    label: 'Tokyo Pink',
    category: 'glow',
    previewText: 'NEON',
    patch: {
      color: '#ffffff',
      fontFamily: 'Righteous',
      fontWeight: 'normal',
      stroke: {
        width: 1.5,
        color: '#ff007f',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 0,
        blur: 26,
        color: '#ff007f',
      },
      letterSpacing: 2,
    },
    previewStyle: {
      color: '#ffffff',
      fontFamily: 'Righteous, sans-serif',
      WebkitTextStroke: '1.5px #ff007f',
      textShadow: '0 0 8px #ff007f, 0 0 22px #ff007f, 0 0 38px #d6006c',
      letterSpacing: '2px',
    },
  },
  {
    id: 'acid-lime',
    label: 'Acid Lime',
    category: 'glow',
    previewText: 'LIME',
    patch: {
      color: '#ffffff',
      fontFamily: 'Syne',
      fontWeight: 'bold',
      stroke: {
        width: 1.5,
        color: '#39ff14',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 0,
        blur: 24,
        color: '#39ff14',
      },
      letterSpacing: 2,
    },
    previewStyle: {
      color: '#ffffff',
      fontFamily: 'Syne, sans-serif',
      WebkitTextStroke: '1.5px #39ff14',
      textShadow: '0 0 8px #39ff14, 0 0 20px #39ff14, 0 0 36px #10b981',
      letterSpacing: '1px',
    },
  },
  {
    id: 'solar-gold',
    label: 'Solar Ray',
    category: 'glow',
    previewText: 'SOLAR',
    patch: {
      color: '#fffbeb',
      fontFamily: 'Anton',
      fontWeight: 'normal',
      stroke: {
        width: 1.5,
        color: '#ffd700',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 0,
        blur: 22,
        color: '#ffaa00',
      },
      letterSpacing: 1.5,
    },
    previewStyle: {
      color: '#fffbeb',
      fontFamily: 'Anton, sans-serif',
      WebkitTextStroke: '1.5px #ffd700',
      textShadow: '0 0 8px #ffd700, 0 0 22px #ff9900, 0 0 40px #ff5500',
      letterSpacing: '1.5px',
    },
  },
  {
    id: 'purple-nebula',
    label: 'Nebula Purple',
    category: 'glow',
    previewText: 'VIBE',
    patch: {
      color: '#ffffff',
      fontFamily: 'Righteous',
      fontWeight: 'normal',
      stroke: {
        width: 1.5,
        color: '#c084fc',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 0,
        blur: 24,
        color: '#a855f7',
      },
      letterSpacing: 1.5,
    },
    previewStyle: {
      color: '#ffffff',
      fontFamily: 'Righteous, sans-serif',
      WebkitTextStroke: '1.5px #c084fc',
      textShadow: '0 0 8px #c084fc, 0 0 22px #9333ea, 0 0 38px #6b21a8',
      letterSpacing: '1.5px',
    },
  },
  {
    id: 'ice-blizzard',
    label: 'Ice Blizzard',
    category: 'glow',
    previewText: 'FROST',
    patch: {
      color: '#e0f2fe',
      fontFamily: 'Montserrat',
      fontWeight: 'bold',
      stroke: {
        width: 1.5,
        color: '#38bdf8',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 0,
        blur: 24,
        color: '#0284c7',
      },
      letterSpacing: 2,
    },
    previewStyle: {
      color: '#e0f2fe',
      fontFamily: 'Montserrat, sans-serif',
      WebkitTextStroke: '1.5px #38bdf8',
      textShadow: '0 0 8px #38bdf8, 0 0 20px #0284c7, 0 0 35px #0369a1',
      letterSpacing: '2px',
    },
  },
  {
    id: 'electric-amber',
    label: 'Electric Surge',
    category: 'glow',
    previewText: 'VOLT',
    patch: {
      color: '#fef08a',
      fontFamily: 'Anton',
      fontWeight: 'normal',
      stroke: {
        width: 1.5,
        color: '#eab308',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 0,
        blur: 22,
        color: '#ca8a04',
      },
      letterSpacing: 2,
    },
    previewStyle: {
      color: '#fef08a',
      fontFamily: 'Anton, sans-serif',
      WebkitTextStroke: '1.5px #eab308',
      textShadow: '0 0 8px #facc15, 0 0 22px #eab308, 0 0 36px #ca8a04',
      letterSpacing: '1.5px',
    },
  },
  {
    id: 'emerald-laser',
    label: 'Emerald Laser',
    category: 'glow',
    previewText: 'JADE',
    patch: {
      color: '#ecfdf5',
      fontFamily: 'Orbitron',
      fontWeight: 'bold',
      stroke: {
        width: 1.5,
        color: '#10b981',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 0,
        blur: 24,
        color: '#059669',
      },
      letterSpacing: 2,
    },
    previewStyle: {
      color: '#ecfdf5',
      fontFamily: 'Orbitron, sans-serif',
      WebkitTextStroke: '1.5px #10b981',
      textShadow: '0 0 8px #10b981, 0 0 22px #059669, 0 0 38px #047857',
      letterSpacing: '2px',
    },
  },
  {
    id: 'blood-moon-glow',
    label: 'Blood Moon',
    category: 'glow',
    previewText: 'BLOOD',
    patch: {
      color: '#ffffff',
      fontFamily: 'Russo One',
      fontWeight: 'normal',
      stroke: {
        width: 1.8,
        color: '#ef4444',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 0,
        blur: 28,
        color: '#dc2626',
      },
      letterSpacing: 2,
    },
    previewStyle: {
      color: '#ffffff',
      fontFamily: 'Russo One, sans-serif',
      WebkitTextStroke: '1.5px #ef4444',
      textShadow: '0 0 10px #ef4444, 0 0 25px #dc2626, 0 0 45px #991b1b',
      letterSpacing: '2px',
    },
  },
  {
    id: 'ultraviolet-pulse',
    label: 'UV Pulse',
    category: 'glow',
    previewText: 'PULSE',
    patch: {
      color: '#f5f3ff',
      fontFamily: 'Syne',
      fontWeight: 'bold',
      stroke: {
        width: 1.5,
        color: '#8b5cf6',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 0,
        blur: 26,
        color: '#6d28d9',
      },
      letterSpacing: 2.5,
    },
    previewStyle: {
      color: '#f5f3ff',
      fontFamily: 'Syne, sans-serif',
      WebkitTextStroke: '1.5px #8b5cf6',
      textShadow: '0 0 10px #8b5cf6, 0 0 25px #7c3aed, 0 0 40px #4c1d95',
      letterSpacing: '2px',
    },
  },
  {
    id: 'atomic-orange',
    label: 'Atomic Flare',
    category: 'glow',
    previewText: 'FLARE',
    patch: {
      color: '#fff7ed',
      fontFamily: 'Anton',
      fontWeight: 'normal',
      stroke: {
        width: 1.5,
        color: '#f97316',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 0,
        blur: 24,
        color: '#ea580c',
      },
      letterSpacing: 1.5,
    },
    previewStyle: {
      color: '#fff7ed',
      fontFamily: 'Anton, sans-serif',
      WebkitTextStroke: '1.5px #f97316',
      textShadow: '0 0 8px #f97316, 0 0 22px #ea580c, 0 0 38px #c2410c',
      letterSpacing: '1.5px',
    },
  },
  {
    id: 'pure-white-starlight',
    label: 'Star Diamond',
    category: 'glow',
    previewText: 'SHINE',
    patch: {
      color: '#ffffff',
      fontFamily: 'Montserrat',
      fontWeight: 'bold',
      stroke: {
        width: 1.2,
        color: '#e2e8f0',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 0,
        blur: 24,
        color: '#ffffff',
      },
      letterSpacing: 2,
    },
    previewStyle: {
      color: '#ffffff',
      fontFamily: 'Montserrat, sans-serif',
      WebkitTextStroke: '1.2px #ffffff',
      textShadow: '0 0 10px #ffffff, 0 0 25px #cbd5e1, 0 0 40px #94a3b8',
      letterSpacing: '2px',
    },
  },
  {
    id: 'comic-boom',
    label: 'Comic Boom',
    category: '3d',
    previewText: 'BOOM!',
    patch: {
      color: '#ffe600',
      fontFamily: 'Bangers',
      fontWeight: 'normal',
      stroke: {
        width: 3,
        color: '#000000',
      },
      textShadow: {
        offsetX: 6,
        offsetY: 6,
        blur: 0,
        color: '#ff0055',
      },
      letterSpacing: 1.5,
    },
    previewStyle: {
      color: '#ffe600',
      fontFamily: 'Bangers, cursive',
      WebkitTextStroke: '2px #000000',
      textShadow: '2px 2px 0 #000, 4px 4px 0 #000, 6px 6px 0 #ff0055',
      letterSpacing: '1px',
    },
  },
  {
    id: 'lucky-bubble',
    label: 'Lucky Bubble',
    category: '3d',
    previewText: 'POPPY',
    patch: {
      color: '#38bdf8',
      fontFamily: 'Luckiest Guy',
      fontWeight: 'normal',
      stroke: {
        width: 2.5,
        color: '#0284c7',
      },
      textShadow: {
        offsetX: 5,
        offsetY: 5,
        blur: 0,
        color: '#0c4a6e',
      },
      letterSpacing: 1,
    },
    previewStyle: {
      color: '#38bdf8',
      fontFamily: 'Luckiest Guy, cursive',
      WebkitTextStroke: '1.5px #0284c7',
      textShadow: '2px 2px 0 #0369a1, 4px 4px 0 #0c4a6e, 6px 6px 0 #082f49',
      letterSpacing: '1px',
    },
  },
  {
    id: 'hot-inferno',
    label: 'Hot Inferno',
    category: '3d',
    previewText: 'FIRE',
    patch: {
      color: '#ff4500',
      fontFamily: 'Russo One',
      fontWeight: 'normal',
      stroke: {
        width: 2,
        color: '#ffcc00',
      },
      textShadow: {
        offsetX: 4,
        offsetY: 5,
        blur: 4,
        color: '#7f1d1d',
      },
      letterSpacing: 1.5,
    },
    previewStyle: {
      color: '#ff3b00',
      fontFamily: 'Russo One, sans-serif',
      WebkitTextStroke: '1.5px #ffcc00',
      textShadow: '2px 2px 0 #dc2626, 4px 4px 0 #991b1b, 6px 6px 8px #450a0a',
      letterSpacing: '1px',
    },
  },
  {
    id: 'bubblegum-pink-3d',
    label: 'Sweet Candy',
    category: '3d',
    previewText: 'SWEET',
    patch: {
      color: '#f472b6',
      fontFamily: 'Fredoka',
      fontWeight: 'bold',
      stroke: {
        width: 2,
        color: '#db2777',
      },
      textShadow: {
        offsetX: 4,
        offsetY: 5,
        blur: 0,
        color: '#831843',
      },
      letterSpacing: 1,
    },
    previewStyle: {
      color: '#f472b6',
      fontFamily: 'Fredoka, sans-serif',
      WebkitTextStroke: '1.5px #db2777',
      textShadow: '2px 2px 0 #be185d, 4px 4px 0 #831843',
      letterSpacing: '1px',
    },
  },
  {
    id: 'arcade-retro-green',
    label: 'Arcade 8-Bit',
    category: '3d',
    previewText: '8-BIT',
    patch: {
      color: '#22c55e',
      fontFamily: 'Press Start 2P',
      fontWeight: 'normal',
      stroke: {
        width: 2,
        color: '#14532d',
      },
      textShadow: {
        offsetX: 5,
        offsetY: 5,
        blur: 0,
        color: '#052e16',
      },
      letterSpacing: 1,
    },
    previewStyle: {
      color: '#22c55e',
      fontFamily: '"Press Start 2P", monospace',
      textShadow: '2px 2px 0 #15803d, 4px 4px 0 #14532d, 6px 6px 0 #052e16',
      fontSize: '11px',
      letterSpacing: '0px',
    },
  },
  {
    id: 'clay-dough-yellow',
    label: 'Clay Yellow',
    category: '3d',
    previewText: 'CLAY',
    patch: {
      color: '#facc15',
      fontFamily: 'Luckiest Guy',
      fontWeight: 'normal',
      stroke: {
        width: 2,
        color: '#ca8a04',
      },
      textShadow: {
        offsetX: 5,
        offsetY: 5,
        blur: 0,
        color: '#713f12',
      },
      letterSpacing: 1,
    },
    previewStyle: {
      color: '#facc15',
      fontFamily: 'Luckiest Guy, cursive',
      WebkitTextStroke: '1.5px #ca8a04',
      textShadow: '2px 2px 0 #a16207, 4px 4px 0 #713f12, 6px 6px 0 #422006',
      letterSpacing: '1px',
    },
  },
  {
    id: 'cyber-extrude-3d',
    label: 'Cyber Extrude',
    category: '3d',
    previewText: 'EXTRUDE',
    patch: {
      color: '#e0f2fe',
      fontFamily: 'Black Ops One',
      fontWeight: 'normal',
      stroke: {
        width: 2,
        color: '#0284c7',
      },
      textShadow: {
        offsetX: 6,
        offsetY: 6,
        blur: 0,
        color: '#0f172a',
      },
      letterSpacing: 2,
    },
    previewStyle: {
      color: '#e0f2fe',
      fontFamily: '"Black Ops One", sans-serif',
      WebkitTextStroke: '1.5px #0284c7',
      textShadow: '2px 2px 0 #0369a1, 4px 4px 0 #075985, 6px 6px 0 #0f172a',
      letterSpacing: '1.5px',
    },
  },
  {
    id: 'lava-crust-3d',
    label: 'Magma 3D',
    category: '3d',
    previewText: 'MAGMA',
    patch: {
      color: '#fb923c',
      fontFamily: 'Russo One',
      fontWeight: 'normal',
      stroke: {
        width: 2,
        color: '#9a3412',
      },
      textShadow: {
        offsetX: 5,
        offsetY: 6,
        blur: 2,
        color: '#431407',
      },
      letterSpacing: 1.5,
    },
    previewStyle: {
      color: '#fb923c',
      fontFamily: 'Russo One, sans-serif',
      WebkitTextStroke: '1.5px #c2410c',
      textShadow: '2px 2px 0 #9a3412, 4px 4px 0 #7c2d12, 6px 6px 2px #431407',
      letterSpacing: '1px',
    },
  },
  {
    id: 'neon-mint-stack-3d',
    label: 'Mint Pop',
    category: '3d',
    previewText: 'MINT',
    patch: {
      color: '#6ee7b7',
      fontFamily: 'Fredoka',
      fontWeight: 'bold',
      stroke: {
        width: 2,
        color: '#047857',
      },
      textShadow: {
        offsetX: 5,
        offsetY: 5,
        blur: 0,
        color: '#064e3b',
      },
      letterSpacing: 1,
    },
    previewStyle: {
      color: '#6ee7b7',
      fontFamily: 'Fredoka, sans-serif',
      WebkitTextStroke: '1.5px #047857',
      textShadow: '2px 2px 0 #059669, 4px 4px 0 #064e3b, 6px 6px 0 #022c22',
      letterSpacing: '1px',
    },
  },
  {
    id: 'shadow-block-blackops',
    label: 'Block Ops',
    category: '3d',
    previewText: 'OPS',
    patch: {
      color: '#f8fafc',
      fontFamily: 'Black Ops One',
      fontWeight: 'normal',
      stroke: {
        width: 2,
        color: '#334155',
      },
      textShadow: {
        offsetX: 6,
        offsetY: 6,
        blur: 0,
        color: '#020617',
      },
      letterSpacing: 2,
    },
    previewStyle: {
      color: '#f8fafc',
      fontFamily: '"Black Ops One", sans-serif',
      WebkitTextStroke: '1.5px #475569',
      textShadow: '2px 2px 0 #334155, 4px 4px 0 #1e293b, 6px 6px 0 #020617',
      letterSpacing: '1px',
    },
  },
  {
    id: 'retro-shadow-yellow-red',
    label: 'Red Shadow 3D',
    category: '3d',
    previewText: 'HERO',
    patch: {
      color: '#fef08a',
      fontFamily: 'Bebas Neue',
      fontWeight: 'normal',
      stroke: {
        width: 2,
        color: '#b91c1c',
      },
      textShadow: {
        offsetX: 6,
        offsetY: 6,
        blur: 0,
        color: '#7f1d1d',
      },
      letterSpacing: 2,
    },
    previewStyle: {
      color: '#fef08a',
      fontFamily: 'Bebas Neue, sans-serif',
      WebkitTextStroke: '1.5px #b91c1c',
      textShadow: '2px 2px 0 #dc2626, 4px 4px 0 #991b1b, 6px 6px 0 #7f1d1d',
      letterSpacing: '2px',
    },
  },
  {
    id: 'purple-pop-cartoon',
    label: 'Purple POP',
    category: '3d',
    previewText: 'POP!',
    patch: {
      color: '#e879f9',
      fontFamily: 'Luckiest Guy',
      fontWeight: 'normal',
      stroke: {
        width: 2,
        color: '#701a75',
      },
      textShadow: {
        offsetX: 5,
        offsetY: 5,
        blur: 0,
        color: '#4a044e',
      },
      letterSpacing: 1,
    },
    previewStyle: {
      color: '#e879f9',
      fontFamily: 'Luckiest Guy, cursive',
      WebkitTextStroke: '1.5px #86198f',
      textShadow: '2px 2px 0 #701a75, 4px 4px 0 #4a044e',
      letterSpacing: '1px',
    },
  },
  {
    id: 'gold-crown',
    label: 'Gold 24K',
    category: 'chrome',
    previewText: 'GOLD',
    patch: {
      color: '#fef08a',
      fontFamily: 'Cinzel',
      fontWeight: 'bold',
      stroke: {
        width: 1.5,
        color: '#b45309',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 3,
        blur: 10,
        color: '#78350f',
      },
      letterSpacing: 2,
    },
    previewStyle: {
      color: '#fef08a',
      fontFamily: 'Cinzel, serif',
      WebkitTextStroke: '1px #b45309',
      textShadow: '0 2px 4px rgba(0,0,0,0.6), 0 0 14px #eab308, 0 4px 8px #78350f',
      letterSpacing: '2px',
    },
  },
  {
    id: 'silver-chrome',
    label: 'Chrome Silver',
    category: 'chrome',
    previewText: 'CHROME',
    patch: {
      color: '#f8fafc',
      fontFamily: 'Syne',
      fontWeight: 'bold',
      stroke: {
        width: 1.5,
        color: '#64748b',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 3,
        blur: 8,
        color: '#0f172a',
      },
      letterSpacing: 3,
    },
    previewStyle: {
      color: '#f8fafc',
      fontFamily: 'Syne, sans-serif',
      WebkitTextStroke: '1.2px #94a3b8',
      textShadow: '0 2px 6px rgba(0,0,0,0.8), 0 0 16px #cbd5e1, 0 3px 6px #334155',
      letterSpacing: '2px',
    },
  },
  {
    id: 'bronze-medal',
    label: 'Ancient Bronze',
    category: 'chrome',
    previewText: 'BRONZE',
    patch: {
      color: '#fed7aa',
      fontFamily: 'Cinzel',
      fontWeight: 'bold',
      stroke: {
        width: 1.5,
        color: '#9a3412',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 3,
        blur: 10,
        color: '#431407',
      },
      letterSpacing: 2,
    },
    previewStyle: {
      color: '#fed7aa',
      fontFamily: 'Cinzel, serif',
      WebkitTextStroke: '1px #9a3412',
      textShadow: '0 2px 5px rgba(0,0,0,0.7), 0 0 12px #ea580c, 0 4px 8px #431407',
      letterSpacing: '2px',
    },
  },
  {
    id: 'rose-gold-luxury',
    label: 'Rose Gold',
    category: 'chrome',
    previewText: 'ROSE',
    patch: {
      color: '#fce7f3',
      fontFamily: 'Playfair Display',
      fontWeight: 'bold',
      stroke: {
        width: 1.2,
        color: '#be185d',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 3,
        blur: 10,
        color: '#831843',
      },
      letterSpacing: 2,
    },
    previewStyle: {
      color: '#fce7f3',
      fontFamily: 'Playfair Display, serif',
      WebkitTextStroke: '1px #db2777',
      textShadow: '0 2px 6px rgba(0,0,0,0.6), 0 0 14px #f472b6, 0 3px 6px #831843',
      letterSpacing: '2px',
    },
  },
  {
    id: 'platinum-mirror',
    label: 'Platinum',
    category: 'chrome',
    previewText: 'PLATINUM',
    patch: {
      color: '#ffffff',
      fontFamily: 'Montserrat',
      fontWeight: 'bold',
      stroke: {
        width: 1.2,
        color: '#94a3b8',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 3,
        blur: 12,
        color: '#475569',
      },
      letterSpacing: 2.5,
    },
    previewStyle: {
      color: '#ffffff',
      fontFamily: 'Montserrat, sans-serif',
      WebkitTextStroke: '1px #cbd5e1',
      textShadow: '0 2px 8px rgba(0,0,0,0.7), 0 0 18px #e2e8f0, 0 3px 8px #334155',
      letterSpacing: '2px',
    },
  },
  {
    id: 'obsidian-titanium',
    label: 'Black Obsidian',
    category: 'chrome',
    previewText: 'OBSIDIAN',
    patch: {
      color: '#0f172a',
      fontFamily: 'Russo One',
      fontWeight: 'normal',
      stroke: {
        width: 1.5,
        color: '#38bdf8',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 0,
        blur: 14,
        color: '#0284c7',
      },
      letterSpacing: 2,
    },
    previewStyle: {
      color: '#0f172a',
      fontFamily: 'Russo One, sans-serif',
      WebkitTextStroke: '1.2px #38bdf8',
      textShadow: '0 0 10px #0ea5e9, 0 2px 8px #000000',
      letterSpacing: '2px',
    },
  },
  {
    id: 'royal-brass',
    label: 'Royal Brass',
    category: 'chrome',
    previewText: 'BRASS',
    patch: {
      color: '#fef9c3',
      fontFamily: 'Cinzel',
      fontWeight: 'bold',
      stroke: {
        width: 1.5,
        color: '#a16207',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 3,
        blur: 8,
        color: '#713f12',
      },
      letterSpacing: 2,
    },
    previewStyle: {
      color: '#fef9c3',
      fontFamily: 'Cinzel, serif',
      WebkitTextStroke: '1.2px #ca8a04',
      textShadow: '0 2px 6px rgba(0,0,0,0.6), 0 0 12px #eab308, 0 3px 6px #713f12',
      letterSpacing: '2px',
    },
  },
  {
    id: 'mercury-liquid',
    label: 'Liquid Mercury',
    category: 'chrome',
    previewText: 'MERCURY',
    patch: {
      color: '#e2e8f0',
      fontFamily: 'Syne',
      fontWeight: 'bold',
      stroke: {
        width: 1.5,
        color: '#475569',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 4,
        blur: 10,
        color: '#0f172a',
      },
      letterSpacing: 2.5,
    },
    previewStyle: {
      color: '#e2e8f0',
      fontFamily: 'Syne, sans-serif',
      WebkitTextStroke: '1.2px #64748b',
      textShadow: '0 3px 8px rgba(0,0,0,0.8), 0 0 16px #94a3b8',
      letterSpacing: '2px',
    },
  },
  {
    id: 'copper-burnished',
    label: 'Burnished Copper',
    category: 'chrome',
    previewText: 'COPPER',
    patch: {
      color: '#ffedd5',
      fontFamily: 'Anton',
      fontWeight: 'normal',
      stroke: {
        width: 1.5,
        color: '#c2410c',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 3,
        blur: 8,
        color: '#7c2d12',
      },
      letterSpacing: 1.5,
    },
    previewStyle: {
      color: '#ffedd5',
      fontFamily: 'Anton, sans-serif',
      WebkitTextStroke: '1.2px #ea580c',
      textShadow: '0 2px 6px rgba(0,0,0,0.7), 0 0 14px #f97316, 0 3px 6px #7c2d12',
      letterSpacing: '1.5px',
    },
  },
  {
    id: 'pearl-iridescent',
    label: 'White Pearl',
    category: 'chrome',
    previewText: 'PEARL',
    patch: {
      color: '#f8fafc',
      fontFamily: 'Playfair Display',
      fontWeight: 'bold',
      stroke: {
        width: 1,
        color: '#cbd5e1',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 2,
        blur: 12,
        color: '#bae6fd',
      },
      letterSpacing: 2,
    },
    previewStyle: {
      color: '#f8fafc',
      fontFamily: 'Playfair Display, serif',
      WebkitTextStroke: '1px #cbd5e1',
      textShadow: '0 2px 8px rgba(0,0,0,0.5), 0 0 16px #e0f2fe',
      letterSpacing: '2px',
    },
  },
  {
    id: 'steel-gunmetal',
    label: 'Gunmetal Steel',
    category: 'chrome',
    previewText: 'STEEL',
    patch: {
      color: '#94a3b8',
      fontFamily: 'Russo One',
      fontWeight: 'normal',
      stroke: {
        width: 1.5,
        color: '#1e293b',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 3,
        blur: 6,
        color: '#020617',
      },
      letterSpacing: 2,
    },
    previewStyle: {
      color: '#94a3b8',
      fontFamily: 'Russo One, sans-serif',
      WebkitTextStroke: '1.2px #334155',
      textShadow: '0 2px 6px rgba(0,0,0,0.8), 0 0 10px #64748b',
      letterSpacing: '2px',
    },
  },
  {
    id: 'aurora-chrome',
    label: 'Aurora Chrome',
    category: 'chrome',
    previewText: 'AURORA',
    patch: {
      color: '#ccfbf1',
      fontFamily: 'Orbitron',
      fontWeight: 'bold',
      stroke: {
        width: 1.5,
        color: '#0d9488',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 0,
        blur: 16,
        color: '#2dd4bf',
      },
      letterSpacing: 2,
    },
    previewStyle: {
      color: '#ccfbf1',
      fontFamily: 'Orbitron, sans-serif',
      WebkitTextStroke: '1.2px #14b8a6',
      textShadow: '0 0 12px #2dd4bf, 0 3px 6px rgba(0,0,0,0.6)',
      letterSpacing: '2px',
    },
  },
  {
    id: 'tiktok-bold-stroke',
    label: 'TikTok White',
    category: 'outline',
    previewText: 'TIKTOK',
    patch: {
      color: '#ffffff',
      fontFamily: 'Anton',
      fontWeight: 'normal',
      stroke: {
        width: 3,
        color: '#000000',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 3,
        blur: 6,
        color: 'rgba(0,0,0,0.8)',
      },
      letterSpacing: 2,
    },
    previewStyle: {
      color: '#ffffff',
      fontFamily: 'Anton, sans-serif',
      WebkitTextStroke: '2.5px #000000',
      textShadow: '0 3px 6px rgba(0,0,0,0.9)',
      letterSpacing: '1.5px',
    },
  },
  {
    id: 'yellow-black-hazard',
    label: 'Hazard Yellow',
    category: 'outline',
    previewText: 'CAUTION',
    patch: {
      color: '#facc15',
      fontFamily: 'Bebas Neue',
      fontWeight: 'normal',
      stroke: {
        width: 3,
        color: '#000000',
      },
      textShadow: {
        offsetX: 2,
        offsetY: 2,
        blur: 0,
        color: '#000000',
      },
      letterSpacing: 2,
    },
    previewStyle: {
      color: '#facc15',
      fontFamily: 'Bebas Neue, sans-serif',
      WebkitTextStroke: '2px #000000',
      textShadow: '2px 2px 0 #000, -1px -1px 0 #000',
      letterSpacing: '2px',
    },
  },
  {
    id: 'sticker-white-edge',
    label: 'White Sticker',
    category: 'outline',
    previewText: 'STICKER',
    patch: {
      color: '#09090b',
      fontFamily: 'Fredoka',
      fontWeight: 'bold',
      stroke: {
        width: 3.5,
        color: '#ffffff',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 3,
        blur: 8,
        color: 'rgba(0,0,0,0.6)',
      },
      letterSpacing: 1,
    },
    previewStyle: {
      color: '#09090b',
      fontFamily: 'Fredoka, sans-serif',
      WebkitTextStroke: '3px #ffffff',
      textShadow: '0 3px 8px rgba(0,0,0,0.7)',
      letterSpacing: '1px',
    },
  },
  {
    id: 'cyan-wire-frame',
    label: 'Hollow Cyan',
    category: 'outline',
    previewText: 'HOLLOW',
    patch: {
      color: 'transparent',
      fontFamily: 'Orbitron',
      fontWeight: 'bold',
      stroke: {
        width: 2,
        color: '#00e5ff',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 0,
        blur: 12,
        color: '#00e5ff',
      },
      letterSpacing: 3,
    },
    previewStyle: {
      color: 'transparent',
      fontFamily: 'Orbitron, sans-serif',
      WebkitTextStroke: '2px #00e5ff',
      textShadow: '0 0 10px rgba(0,229,255,0.7)',
      letterSpacing: '2px',
    },
  },
  {
    id: 'red-alert-wire',
    label: 'Danger Red',
    category: 'outline',
    previewText: 'DANGER',
    patch: {
      color: '#ffffff',
      fontFamily: 'Anton',
      fontWeight: 'normal',
      stroke: {
        width: 2.5,
        color: '#dc2626',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 0,
        blur: 14,
        color: '#b91c1c',
      },
      letterSpacing: 2,
    },
    previewStyle: {
      color: '#ffffff',
      fontFamily: 'Anton, sans-serif',
      WebkitTextStroke: '2px #dc2626',
      textShadow: '0 0 10px #ef4444',
      letterSpacing: '1.5px',
    },
  },
  {
    id: 'pink-white-double',
    label: 'Candy Outline',
    category: 'outline',
    previewText: 'CANDY',
    patch: {
      color: '#f43f5e',
      fontFamily: 'Luckiest Guy',
      fontWeight: 'normal',
      stroke: {
        width: 2.5,
        color: '#ffffff',
      },
      textShadow: {
        offsetX: 3,
        offsetY: 3,
        blur: 0,
        color: '#881337',
      },
      letterSpacing: 1,
    },
    previewStyle: {
      color: '#f43f5e',
      fontFamily: 'Luckiest Guy, cursive',
      WebkitTextStroke: '2px #ffffff',
      textShadow: '2px 2px 0 #9f1239, 3px 3px 0 #4c0519',
      letterSpacing: '1px',
    },
  },
  {
    id: 'triple-black-yellow',
    label: 'Vibe Impact',
    category: 'outline',
    previewText: 'IMPACT',
    patch: {
      color: '#ffffff',
      fontFamily: 'Russo One',
      fontWeight: 'normal',
      stroke: {
        width: 2.5,
        color: '#eab308',
      },
      textShadow: {
        offsetX: 3,
        offsetY: 3,
        blur: 0,
        color: '#000000',
      },
      letterSpacing: 1.5,
    },
    previewStyle: {
      color: '#ffffff',
      fontFamily: 'Russo One, sans-serif',
      WebkitTextStroke: '2px #eab308',
      textShadow: '2px 2px 0 #000000, 3px 3px 0 #000000',
      letterSpacing: '1px',
    },
  },
  {
    id: 'green-laser-wire',
    label: 'Hollow Neon',
    category: 'outline',
    previewText: 'WIRE',
    patch: {
      color: 'transparent',
      fontFamily: 'Syne',
      fontWeight: 'bold',
      stroke: {
        width: 2,
        color: '#22c55e',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 0,
        blur: 14,
        color: '#16a34a',
      },
      letterSpacing: 2,
    },
    previewStyle: {
      color: 'transparent',
      fontFamily: 'Syne, sans-serif',
      WebkitTextStroke: '1.8px #22c55e',
      textShadow: '0 0 10px rgba(34,197,94,0.7)',
      letterSpacing: '2px',
    },
  },
  {
    id: 'gold-outline-badge',
    label: 'Gold Inset',
    category: 'outline',
    previewText: 'LUXE',
    patch: {
      color: '#000000',
      fontFamily: 'Cinzel',
      fontWeight: 'bold',
      stroke: {
        width: 2,
        color: '#ffd700',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 0,
        blur: 10,
        color: '#ca8a04',
      },
      letterSpacing: 2,
    },
    previewStyle: {
      color: '#000000',
      fontFamily: 'Cinzel, serif',
      WebkitTextStroke: '1.8px #ffd700',
      textShadow: '0 0 8px #eab308',
      letterSpacing: '2px',
    },
  },
  {
    id: 'magenta-hollow-glam',
    label: 'Hollow Pink',
    category: 'outline',
    previewText: 'GLAM',
    patch: {
      color: 'transparent',
      fontFamily: 'Righteous',
      fontWeight: 'normal',
      stroke: {
        width: 2,
        color: '#ec4899',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 0,
        blur: 14,
        color: '#db2777',
      },
      letterSpacing: 2,
    },
    previewStyle: {
      color: 'transparent',
      fontFamily: 'Righteous, sans-serif',
      WebkitTextStroke: '1.8px #ec4899',
      textShadow: '0 0 10px rgba(236,72,153,0.7)',
      letterSpacing: '2px',
    },
  },
  {
    id: 'blue-double-sport',
    label: 'Sport Stadium',
    category: 'outline',
    previewText: 'STADIUM',
    patch: {
      color: '#3b82f6',
      fontFamily: 'Anton',
      fontWeight: 'normal',
      stroke: {
        width: 2.5,
        color: '#ffffff',
      },
      textShadow: {
        offsetX: 3,
        offsetY: 3,
        blur: 0,
        color: '#1e3a8a',
      },
      letterSpacing: 1.5,
    },
    previewStyle: {
      color: '#3b82f6',
      fontFamily: 'Anton, sans-serif',
      WebkitTextStroke: '2px #ffffff',
      textShadow: '2px 2px 0 #1e40af, 4px 4px 0 #1e3a8a',
      letterSpacing: '1.5px',
    },
  },
  {
    id: 'clean-dark-border',
    label: 'Clean Minimal',
    category: 'outline',
    previewText: 'CLEAN',
    patch: {
      color: '#ffffff',
      fontFamily: 'Montserrat',
      fontWeight: 'bold',
      stroke: {
        width: 1.5,
        color: '#18181b',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 2,
        blur: 4,
        color: 'rgba(0,0,0,0.5)',
      },
      letterSpacing: 2,
    },
    previewStyle: {
      color: '#ffffff',
      fontFamily: 'Montserrat, sans-serif',
      WebkitTextStroke: '1.2px #18181b',
      textShadow: '0 2px 4px rgba(0,0,0,0.6)',
      letterSpacing: '2px',
    },
  },
  {
    id: 'sunset-dream',
    label: 'Sunset Dream',
    category: 'gradient',
    previewText: 'SUNSET',
    patch: {
      color: '#fb923c',
      fontFamily: 'Syne',
      fontWeight: 'bold',
      stroke: {
        width: 1,
        color: '#c2410c',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 3,
        blur: 10,
        color: '#db2777',
      },
      letterSpacing: 2,
    },
    previewStyle: {
      background: 'linear-gradient(135deg, #fbbf24 0%, #f43f5e 50%, #8b5cf6 100%)',
      WebkitBackgroundClip: 'text',
      WebkitTextFillColor: 'transparent',
      fontFamily: 'Syne, sans-serif',
      fontWeight: 'bold',
      letterSpacing: '2px',
    },
  },
  {
    id: 'cyber-skyline',
    label: 'Cyan Purple',
    category: 'gradient',
    previewText: 'SKYLINE',
    patch: {
      color: '#38bdf8',
      fontFamily: 'Orbitron',
      fontWeight: 'bold',
      stroke: {
        width: 1,
        color: '#0284c7',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 0,
        blur: 16,
        color: '#a855f7',
      },
      letterSpacing: 2.5,
    },
    previewStyle: {
      background: 'linear-gradient(135deg, #00f2fe 0%, #4facfe 50%, #9055ff 100%)',
      WebkitBackgroundClip: 'text',
      WebkitTextFillColor: 'transparent',
      fontFamily: 'Orbitron, sans-serif',
      fontWeight: 'bold',
      letterSpacing: '2px',
    },
  },
  {
    id: 'golden-fire-fade',
    label: 'Gold Flame',
    category: 'gradient',
    previewText: 'BLAZE',
    patch: {
      color: '#fef08a',
      fontFamily: 'Anton',
      fontWeight: 'normal',
      stroke: {
        width: 1,
        color: '#ea580c',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 3,
        blur: 8,
        color: '#991b1b',
      },
      letterSpacing: 1.5,
    },
    previewStyle: {
      background: 'linear-gradient(180deg, #fff700 0%, #ff8800 60%, #ff0044 100%)',
      WebkitBackgroundClip: 'text',
      WebkitTextFillColor: 'transparent',
      fontFamily: 'Anton, sans-serif',
      letterSpacing: '1.5px',
    },
  },
  {
    id: 'aurora-borealis-fade',
    label: 'Aurora Mint',
    category: 'gradient',
    previewText: 'AURORA',
    patch: {
      color: '#6ee7b7',
      fontFamily: 'Montserrat',
      fontWeight: 'bold',
      stroke: {
        width: 1,
        color: '#065f46',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 0,
        blur: 14,
        color: '#3b82f6',
      },
      letterSpacing: 2,
    },
    previewStyle: {
      background: 'linear-gradient(135deg, #43e97b 0%, #38f9d7 50%, #3b82f6 100%)',
      WebkitBackgroundClip: 'text',
      WebkitTextFillColor: 'transparent',
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: 'bold',
      letterSpacing: '2px',
    },
  },
  {
    id: 'berry-smoothie-fade',
    label: 'Berry Violet',
    category: 'gradient',
    previewText: 'BERRY',
    patch: {
      color: '#f472b6',
      fontFamily: 'Fredoka',
      fontWeight: 'bold',
      stroke: {
        width: 1,
        color: '#831843',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 3,
        blur: 8,
        color: '#581c87',
      },
      letterSpacing: 1,
    },
    previewStyle: {
      background: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
      WebkitBackgroundClip: 'text',
      WebkitTextFillColor: 'transparent',
      fontFamily: 'Fredoka, sans-serif',
      fontWeight: 'bold',
      letterSpacing: '1px',
    },
  },
  {
    id: 'ocean-deep-blue',
    label: 'Deep Pacific',
    category: 'gradient',
    previewText: 'OCEAN',
    patch: {
      color: '#38bdf8',
      fontFamily: 'Bebas Neue',
      fontWeight: 'normal',
      stroke: {
        width: 1,
        color: '#0369a1',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 3,
        blur: 10,
        color: '#0c4a6e',
      },
      letterSpacing: 2,
    },
    previewStyle: {
      background: 'linear-gradient(180deg, #38bdf8 0%, #1d4ed8 70%, #0f172a 100%)',
      WebkitBackgroundClip: 'text',
      WebkitTextFillColor: 'transparent',
      fontFamily: 'Bebas Neue, sans-serif',
      letterSpacing: '2px',
    },
  },
  {
    id: 'cotton-candy-fade',
    label: 'Cotton Candy',
    category: 'gradient',
    previewText: 'CANDY',
    patch: {
      color: '#fbcfe8',
      fontFamily: 'Fredoka',
      fontWeight: 'bold',
      stroke: {
        width: 1,
        color: '#db2777',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 0,
        blur: 12,
        color: '#38bdf8',
      },
      letterSpacing: 1,
    },
    previewStyle: {
      background: 'linear-gradient(135deg, #fbcfe8 0%, #fda4af 50%, #bae6fd 100%)',
      WebkitBackgroundClip: 'text',
      WebkitTextFillColor: 'transparent',
      fontFamily: 'Fredoka, sans-serif',
      fontWeight: 'bold',
      letterSpacing: '1px',
    },
  },
  {
    id: 'emerald-mint-spark',
    label: 'Emerald Mint',
    category: 'gradient',
    previewText: 'MINT',
    patch: {
      color: '#a7f3d0',
      fontFamily: 'Syne',
      fontWeight: 'bold',
      stroke: {
        width: 1,
        color: '#047857',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 0,
        blur: 12,
        color: '#059669',
      },
      letterSpacing: 2,
    },
    previewStyle: {
      background: 'linear-gradient(135deg, #a7f3d0 0%, #34d399 50%, #059669 100%)',
      WebkitBackgroundClip: 'text',
      WebkitTextFillColor: 'transparent',
      fontFamily: 'Syne, sans-serif',
      fontWeight: 'bold',
      letterSpacing: '2px',
    },
  },
  {
    id: 'neon-citrus-fade',
    label: 'Neon Citrus',
    category: 'gradient',
    previewText: 'CITRUS',
    patch: {
      color: '#fef08a',
      fontFamily: 'Anton',
      fontWeight: 'normal',
      stroke: {
        width: 1,
        color: '#ca8a04',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 0,
        blur: 10,
        color: '#84cc16',
      },
      letterSpacing: 1.5,
    },
    previewStyle: {
      background: 'linear-gradient(135deg, #fef08a 0%, #a3e635 60%, #22c55e 100%)',
      WebkitBackgroundClip: 'text',
      WebkitTextFillColor: 'transparent',
      fontFamily: 'Anton, sans-serif',
      letterSpacing: '1.5px',
    },
  },
  {
    id: 'mystic-violet-indigo',
    label: 'Mystic Indigo',
    category: 'gradient',
    previewText: 'MYSTIC',
    patch: {
      color: '#ddd6fe',
      fontFamily: 'Righteous',
      fontWeight: 'normal',
      stroke: {
        width: 1,
        color: '#7c3aed',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 0,
        blur: 14,
        color: '#4338ca',
      },
      letterSpacing: 2,
    },
    previewStyle: {
      background: 'linear-gradient(135deg, #c084fc 0%, #818cf8 50%, #4f46e5 100%)',
      WebkitBackgroundClip: 'text',
      WebkitTextFillColor: 'transparent',
      fontFamily: 'Righteous, sans-serif',
      letterSpacing: '2px',
    },
  },
  {
    id: 'lava-molten-fade',
    label: 'Molten Lava',
    category: 'gradient',
    previewText: 'MOLTEN',
    patch: {
      color: '#fed7aa',
      fontFamily: 'Russo One',
      fontWeight: 'normal',
      stroke: {
        width: 1,
        color: '#ea580c',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 3,
        blur: 10,
        color: '#7c2d12',
      },
      letterSpacing: 1.5,
    },
    previewStyle: {
      background: 'linear-gradient(180deg, #ffedd5 0%, #fb923c 40%, #dc2626 100%)',
      WebkitBackgroundClip: 'text',
      WebkitTextFillColor: 'transparent',
      fontFamily: 'Russo One, sans-serif',
      letterSpacing: '1.5px',
    },
  },
  {
    id: 'hologram-rainbow',
    label: 'Holo Prism',
    category: 'gradient',
    previewText: 'PRISM',
    patch: {
      color: '#ffffff',
      fontFamily: 'Orbitron',
      fontWeight: 'bold',
      stroke: {
        width: 1,
        color: '#38bdf8',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 0,
        blur: 14,
        color: '#f43f5e',
      },
      letterSpacing: 2.5,
    },
    previewStyle: {
      background: 'linear-gradient(90deg, #ff007f 0%, #00f2fe 33%, #4facfe 66%, #ffd700 100%)',
      WebkitBackgroundClip: 'text',
      WebkitTextFillColor: 'transparent',
      fontFamily: 'Orbitron, sans-serif',
      fontWeight: 'bold',
      letterSpacing: '2px',
    },
  },
  {
    id: 'paris-fashion-serif',
    label: 'Vogue Luxe',
    category: 'aesthetic',
    previewText: 'Vogue',
    patch: {
      color: '#ffffff',
      fontFamily: 'Playfair Display',
      fontWeight: 'bold',
      stroke: {
        width: 0.5,
        color: '#e2e8f0',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 4,
        blur: 12,
        color: 'rgba(0,0,0,0.8)',
      },
      letterSpacing: 3,
    },
    previewStyle: {
      color: '#ffffff',
      fontFamily: 'Playfair Display, serif',
      fontStyle: 'italic',
      textShadow: '0 4px 14px rgba(0,0,0,0.85)',
      letterSpacing: '3px',
    },
  },
  {
    id: 'retro-cherry-diner',
    label: 'Cherry Diner',
    category: 'aesthetic',
    previewText: 'Diner',
    patch: {
      color: '#ef4444',
      fontFamily: 'Lobster',
      fontWeight: 'normal',
      stroke: {
        width: 2,
        color: '#ffffff',
      },
      textShadow: {
        offsetX: 2,
        offsetY: 3,
        blur: 6,
        color: '#7f1d1d',
      },
      letterSpacing: 1,
    },
    previewStyle: {
      color: '#ef4444',
      fontFamily: 'Lobster, cursive',
      WebkitTextStroke: '1.5px #ffffff',
      textShadow: '2px 3px 6px rgba(127,29,29,0.7)',
      letterSpacing: '1px',
    },
  },
  {
    id: 'tokyo-cyber-glitch',
    label: 'Cyber Glitch',
    category: 'aesthetic',
    previewText: 'GLITCH',
    patch: {
      color: '#ffffff',
      fontFamily: 'Orbitron',
      fontWeight: 'bold',
      stroke: {
        width: 1,
        color: '#00e5ff',
      },
      textShadow: {
        offsetX: 3,
        offsetY: 0,
        blur: 0,
        color: '#ff0055',
      },
      letterSpacing: 3,
    },
    previewStyle: {
      color: '#ffffff',
      fontFamily: 'Orbitron, sans-serif',
      WebkitTextStroke: '1px #00e5ff',
      textShadow: '-2px 0 0 #00e5ff, 2px 0 0 #ff0055',
      letterSpacing: '2px',
    },
  },
  {
    id: 'coffee-cream-editorial',
    label: 'Warm Latte',
    category: 'aesthetic',
    previewText: 'Latte',
    patch: {
      color: '#fef3c7',
      fontFamily: 'Playfair Display',
      fontWeight: 'bold',
      stroke: {
        width: 0.8,
        color: '#92400e',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 3,
        blur: 8,
        color: 'rgba(69,26,3,0.7)',
      },
      letterSpacing: 1.5,
    },
    previewStyle: {
      color: '#fef3c7',
      fontFamily: 'Playfair Display, serif',
      fontStyle: 'italic',
      WebkitTextStroke: '0.8px #92400e',
      textShadow: '0 3px 8px rgba(69,26,3,0.7)',
      letterSpacing: '1.5px',
    },
  },
  {
    id: 'polaroid-1994-sepia',
    label: '1994 Sepia',
    category: 'aesthetic',
    previewText: 'Memories',
    patch: {
      color: '#fef3c7',
      fontFamily: 'Caveat',
      fontWeight: 'bold',
      stroke: {
        width: 0.5,
        color: '#78350f',
      },
      textShadow: {
        offsetX: 1,
        offsetY: 2,
        blur: 4,
        color: '#451a03',
      },
      letterSpacing: 1,
    },
    previewStyle: {
      color: '#fef3c7',
      fontFamily: 'Caveat, cursive',
      textShadow: '1px 2px 4px rgba(69,26,3,0.8)',
      letterSpacing: '1px',
      fontSize: '18px',
    },
  },
  {
    id: 'pacific-beach-cursive',
    label: 'Pacific Beach',
    category: 'aesthetic',
    previewText: 'Aloha',
    patch: {
      color: '#38bdf8',
      fontFamily: 'Pacifico',
      fontWeight: 'normal',
      stroke: {
        width: 1.5,
        color: '#ffffff',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 3,
        blur: 8,
        color: '#0369a1',
      },
      letterSpacing: 1,
    },
    previewStyle: {
      color: '#38bdf8',
      fontFamily: 'Pacifico, cursive',
      WebkitTextStroke: '1px #ffffff',
      textShadow: '0 3px 8px rgba(3,105,161,0.7)',
      letterSpacing: '1px',
    },
  },
  {
    id: 'french-riviera-chic',
    label: 'Riviera Chic',
    category: 'aesthetic',
    previewText: 'RIVIERA',
    patch: {
      color: '#f8fafc',
      fontFamily: 'Cinzel',
      fontWeight: 'bold',
      stroke: {
        width: 0.8,
        color: '#0284c7',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 3,
        blur: 10,
        color: 'rgba(2,132,199,0.5)',
      },
      letterSpacing: 3,
    },
    previewStyle: {
      color: '#f8fafc',
      fontFamily: 'Cinzel, serif',
      WebkitTextStroke: '0.8px #38bdf8',
      textShadow: '0 3px 10px rgba(2,132,199,0.5)',
      letterSpacing: '3px',
    },
  },
  {
    id: 'film-noir-contrast',
    label: 'Film Noir',
    category: 'aesthetic',
    previewText: 'NOIR',
    patch: {
      color: '#ffffff',
      fontFamily: 'Anton',
      fontWeight: 'normal',
      stroke: {
        width: 1,
        color: '#000000',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 4,
        blur: 16,
        color: '#000000',
      },
      letterSpacing: 3,
    },
    previewStyle: {
      color: '#ffffff',
      fontFamily: 'Anton, sans-serif',
      textShadow: '0 4px 16px #000000, 0 1px 2px #000000',
      letterSpacing: '3px',
    },
  },
  {
    id: 'marker-street-art',
    label: 'Street Tag',
    category: 'aesthetic',
    previewText: 'TAG',
    patch: {
      color: '#facc15',
      fontFamily: 'Permanent Marker',
      fontWeight: 'normal',
      stroke: {
        width: 1.5,
        color: '#000000',
      },
      textShadow: {
        offsetX: 3,
        offsetY: 3,
        blur: 0,
        color: '#ef4444',
      },
      letterSpacing: 1,
    },
    previewStyle: {
      color: '#facc15',
      fontFamily: '"Permanent Marker", cursive',
      WebkitTextStroke: '1px #000000',
      textShadow: '2px 2px 0 #ef4444',
      letterSpacing: '1px',
    },
  },
  {
    id: 'neo-tokyo-kanji',
    label: 'Neo Shibuya',
    category: 'aesthetic',
    previewText: 'SHIBUYA',
    patch: {
      color: '#f43f5e',
      fontFamily: 'Syne',
      fontWeight: 'bold',
      stroke: {
        width: 1.2,
        color: '#000000',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 0,
        blur: 14,
        color: '#e11d48',
      },
      letterSpacing: 2.5,
    },
    previewStyle: {
      color: '#f43f5e',
      fontFamily: 'Syne, sans-serif',
      WebkitTextStroke: '1px #000000',
      textShadow: '0 0 12px #e11d48',
      letterSpacing: '2px',
    },
  },
  {
    id: 'lofi-chillwave-dream',
    label: 'Chill Wave',
    category: 'aesthetic',
    previewText: 'Chill',
    patch: {
      color: '#c4b5fd',
      fontFamily: 'Caveat',
      fontWeight: 'bold',
      stroke: {
        width: 0.5,
        color: '#5b21b6',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 2,
        blur: 8,
        color: '#4c1d95',
      },
      letterSpacing: 1.5,
    },
    previewStyle: {
      color: '#c4b5fd',
      fontFamily: 'Caveat, cursive',
      textShadow: '0 2px 8px rgba(91,33,182,0.8)',
      letterSpacing: '1px',
      fontSize: '18px',
    },
  },
  {
    id: 'editorial-italic-gold',
    label: 'Golden Hour',
    category: 'aesthetic',
    previewText: 'Aura',
    patch: {
      color: '#fef08a',
      fontFamily: 'Playfair Display',
      fontWeight: 'bold',
      stroke: {
        width: 0.8,
        color: '#b45309',
      },
      textShadow: {
        offsetX: 0,
        offsetY: 3,
        blur: 8,
        color: 'rgba(180,83,9,0.6)',
      },
      letterSpacing: 2,
    },
    previewStyle: {
      color: '#fef08a',
      fontFamily: 'Playfair Display, serif',
      fontStyle: 'italic',
      WebkitTextStroke: '0.8px #b45309',
      textShadow: '0 3px 8px rgba(180,83,9,0.6)',
      letterSpacing: '2px',
    },
  },
] as const
